### ISSUE TITLE
Built-in IKEv2 android instead of StrongSwan

### ISSUE THREAD

**Issue by theautomation** [hwdsl2/setup-ipsec-vpn#1002]
Hi, I was wondering if it is possible to use the built-in android client instead of StrongSwan, The options on my OnePlus device in Settings  > Wi-Fi & Network > VPN are:

-  IKEv2/IPSec MSCHAPv2
-  IKEv2/IPSec PSK
-  IKEv2/IPSec RSA

Has anyone gotten it working through the native Android app using any of the three options above?

**Comment by letoams** [comment]
On Wed, 18 Aug 2021, Coen Stam wrote:

> Hi, I was wondering if it is possible to use the built-in android client instead of StrongSwan, The options on
> my OnePlus device in Settings > Wi-Fi & Network > VPN are:
>
>  *  IKEv2/IPSec MSCHAPv2
>  *  IKEv2/IPSec PSK
>  *  IKEv2/IPSec RSA
> 
> Has anyone gotten it working through the native Android app using any of the three options above?

I'm interested to hear about this too. with strongswan, you cannot keep
a tunnel up because when the phone goes to sleep, strongswan can't keep
sending keepalives/liveness packets, as it is an application that is
put to sleep. The native implementation hopefull does not have these
problems.

**Comment by keliew** [comment]
It works natively. I use IKEv2/IPSec PSK.

No other clients installed on the android phone.

**Comment by theautomation** [comment]
Can you explain how you did that? I have imported the .p12 file on my Android phone and selected the certifcates in the build-in client. But i cant connect. When im using StrongSwan it is working correctly.

**Comment by keliew** [comment]
You don't need to import anything...just create a new VPN connection, fill in the necessary information, and you're good to go.

**Comment by theautomation** [comment]
Hm sorry you using IKEv2/IPSec PSK so no certificate is needed of course :). I have tried IKEv2/IPSec PSK but also with this protocol i cant connect and don't know why L2TP/IPSec PSK and StrongSwan client but for some reason IKEv2/IPSec PSK does not

![Screenshot_20210819-181038.jpg](https://user-images.githubusercontent.com/43297525/130104041-69ae6522-0e71-4b9b-8499-1b28695f29e0.jpg)

The .env file contains

```
VPN_DISABLE_IPSEC_L2TP=yes
VPN_DISABLE_IPSEC_XAUTH=yes
VPN_IKEV2_ONLY=yes

# Define IPsec PSK, VPN username and password
# DO NOT put "" or '' around values, or add space around =
# DO NOT use these special characters within values: \ " '
VPN_IPSEC_PSK=example
VPN_PASSWORD=
VPN_USER=

# Define additional VPN users
# DO NOT put "" or '' around values, or add space around =
# DO NOT use these special characters within values: \ " '
# Usernames and passwords must be separated by spaces
# VPN_ADDL_USERS=additional_username_1 additional_username_2
# VPN_ADDL_PASSWORDS=additional_password_1 additional_password_2

# Use a DNS name for the VPN server
# The DNS name must be a fully qualified domain name (FQDN)
VPN_DNS_NAME=vpn.theautomation.nl

# Specify a name for the first IKEv2 client
# Use one word only, no special characters except '-' and '_'
# The default is 'vpnclient' if not specified
VPN_CLIENT_NAME=coen

# Use alternative DNS servers
VPN_DNS_SRV1=192.168.1.4
VPN_DNS_SRV2=8.8.8.8
```

**Comment by ninthbar** [comment]
请问如何实现服务端主动断开选定的客户端连接？
比如，ipsec show，ipsec trafficstatus，ipsec status都可以看到有很多客户端连上来了，我想断开部分客户，如何实现？

**Comment by hwdsl2** [comment]
@ninthbar 请参见 #1011.

**Comment by hwdsl2** [comment]
@theautomation Regarding using the built-in IKEv2 VPN client on Android:
1. This project only supports certificate-based authentication for IKEv2, which means two of the three options you mentioned, "IKEv2/IPSec MSCHAPv2" and "IKEv2/IPSec PSK", won't work.
2. For the third option, "IKEv2/IPSec RSA", unfortunately the built-in VPN client in the latest Android version seems to have bugs. Although you can successfully add a VPN connection with type "IKEv2/IPSec RSA", you cannot connect because clicking on the created VPN connection brings up the "Edit VPN profile" dialog, instead of allowing you to connect.

Therefore it is not currently possible to use the built-in IKEv2 VPN client on Android with this project. Please instead use the strongSwan VPN client as mentioned in the docs [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
