### ISSUE TITLE
Multiple L2TP-IPsec clients 

### ISSUE THREAD

**Issue by aamarques** [hwdsl2/setup-ipsec-vpn#1018]
Hi.
I think this isn't a bug but a configuration that I can't deal with alone.
I have configured a VPN Server on a Debian 9 VM in GCP and a client in a Chrome book and another in a windows machine (in my home network).
Everything seems to be ok only if one of both is connected alone. When I try to connect both the connection is closed and no one has a usable connection.

I'm using the default configuration from vpn.sh script.

What can I do to solve this?

Thanks for your help.

**Comment by hwdsl2** [comment]
@aamarques Hello! Due to an IPsec/L2TP limitation [1], if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) or [IPsec/XAuth](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md) mode. For your use case, the Chrome book can connect using IPsec/L2TP mode (because IKEv2 is not supported on this OS), while the windows machine can connect using IKEv2 mode.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by aamarques** [comment]
Thanks for your time.
The scenario above is a test scenario. Now my problem is bigger because I will use 8 Chromebooks in a remote office and behind the same NAT. AS Chromebook can use certificates but is not IKEv2 compatible (and seems not compatible with XAuth), Is there a solution or do I need to use OpenVPN?
Thanks for your support

**Comment by hwdsl2** [comment]
@aamarques For this use case you can try OpenVPN. A setup script is available at:
https://github.com/Nyr/openvpn-install
