### ISSUE TITLE
How to point a domain name

### ISSUE THREAD

**Issue by mannguyen0107** [hwdsl2/setup-ipsec-vpn#1029]
Hi, I'm trying to setup a domain name to connect to my VPN server instead of using the public ipaddress. So I'm pointing my vpn.example.com to my VPN Server through port 500 but it cannot connect. Is it possible to achieve using L2TP IPSEC VPN?

**Comment by mannguyen0107** [comment]
Also, I wanted to add I suspect this is because L2TP using 2 PORT 500 and 4500 and I don't think it is possible to point vpn.example.com to 2 port or at least i dont know how to set it up

**Comment by Scottpedia** [comment]
@mannguyen0107 

Regarding your question, it can't be simpler than just adding a DNS record that associates your server IP to your domain. There is no "binding" of a particular port that you talked about. In most cases, the client OS looks up the input domain name and then use the translated IP address directly. It's basically a replacement action for convenience purposes... 

However, keep in mind that when using IKEv2, the domain name to connect to has to match the correct IP address as declared in the certificates. So in that case, you will have to make sure the DNS record in use is properly set up in relation to the server-side certificates.

**Comment by mannguyen0107** [comment]
@Scottpedia thank you very much for the reply. Here is a more detailed of my setup currently:

I have a linux server running at home and I use that as a VPN server. So in order for clients to connect to my VPN server I have to add NAT in my router i added for port 500 and 4500 to point to my VPN server. That works fine if clients use my public ip to connect. However I would want to use a domain so to protect my public IP. I've setup a DNS in cloudflare lets say vpn.example.com pointing to my public IP. And then I used Kemp (loadbalancer it is just like using nginx for reverse proxy) to redirect the :443 coming from vpn.example.com to point that to my server because cloudflare only use 443, 80. Where it is confusing to me is the VPN server uses 2 port 500 for auth and 4500 for communication and in Kemp I have don't really know how to point that 443 to 500 for auth and 4500 for communication. I'm very new to all this. Been searching for 2 days without luck.

Correctly if I'm wrong but with my case I would be better using IKEv2 right? since it only uses 1 port 500. In that case, how do I get the cert and private key so I can give cloudflare that to sign or am I wrong?

**Comment by Scottpedia** [comment]
@mannguyen0107 

Well, I believe you have certain misunderstandings at this point... 

> That works fine if clients use my public ip to connect. However I would want to use a domain so to protect my public IP. 

First, adding a domain that points to your server's public IP does not protect itself from attacks and alike, if that's what you meant... There is one, or more, IP addresses behind every domain name, which can be looked up basically by anyone. The idea of the DNS was solely for convenience purposes at its invention. 

> I've setup a DNS in cloudflare lets say vpn.example.com pointing to my public IP.

If you want to "protect" your host by using cloudflare proxy, that only works at [certain ports](https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy) for TCP traffic if I am not mistaken.(while IPSec uses UDP) And such a setup is only by design suitable for web applications like a website. To use cloudflare DNS correctly with an IPSec VPN server, you have to disable the proxy option for the DNS record pointing to your server, which in turn exposes your host's identity...

> And then I used Kemp (loadbalancer it is just like using nginx for reverse proxy) to redirect the :443 coming from vpn.example.com to point that to my server because cloudflare only use 443, 80.

Sorry I am not familar with Kemp as you mentioned... So I can't comment on that. But If I were you, I wouldn't have such a complex setup involving proxies or relays between the actual VPN server and the clients.

**Comment by mannguyen0107** [comment]
@Scottpedia Ahhhhh thank you for the information. So for convenience if I setup my domain and turn off the proxy in cloudflare it would point the traffic to the correct port instead of 443 or 80 only. Let me try that.

**Comment by mannguyen0107** [comment]
@Scottpedia yep turned off the proxy in cloudflare works. The reason why I setup vpn at home is because i have some server running and I would want to connect to them when i'm out. I think it would be safer if I have VPN server in the cloud and open the SSH port in my router that only allow traffic coming from the public ip of the VPN server wouldn't you say so?

**Comment by Scottpedia** [comment]
yeah that's not a bad idea. But to do so I personally would just modify the listening port of the SSH server to a non-default one like 48943. Scanning the open ports of a host is usually a very resource and timing intensive task for any spammer to perform on a random host.

All the best.

**Comment by mannguyen0107** [comment]
@Scottpedia Thank you for your help and informations saved me from reading tons of stuff and getting now where :D.
