### ISSUE TITLE
VPN + tor + anonsurf no work

### ISSUE THREAD

**Issue by AnonymousWebHacker** [hwdsl2/setup-ipsec-vpn#1043]
in a vps, if you install the vpn first, and then run tor + anonsurf, the clients can connect, but it doesn't give you internet

**Comment by hwdsl2** [comment]
@AnonymousWebHacker Hello! This use case is not supported. When you connect the VPS to Tor and anonsurf, traffic from the VPS would likely go through the Tor network. Unfortunately, VPN clients will not be able to connect to the Internet using this connection, because the default IPTables rules added by the VPN scripts don't support this use case.

**Comment by AnonymousWebHacker** [comment]
@hwdsl2 I understand, thanks for that question. What adjustments can I make to the iptable to allow that traffic to the tor network?

**Comment by hwdsl2** [comment]
@AnonymousWebHacker Unfortunately, I am not aware of a way to change IPTables rules to make this work.
