### ISSUE TITLE
It is not possible to connect 2 clients from 1 ip

### ISSUE THREAD

**Issue by Kitanit** [hwdsl2/setup-ipsec-vpn#1045]
I noticed that if 2 clients have 1 ip (local network), only 1 can connect to the VPN, can you fix it in the config?

**Comment by hwdsl2** [comment]
@Kitanit Hello! As mentioned in the important notes [1], due to an IPsec/L2TP limitation, if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) or [IPsec/XAuth](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md) mode.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
