### ISSUE TITLE
Any way to check users' connect time?

### ISSUE THREAD

**Issue by peterjpxie** [hwdsl2/setup-ipsec-vpn#105]
Hi Lin Song

In [PPTP VPN](https://github.com/viljoviitanen/setup-simple-pptp-vpn),  we can use ac command to check the user's connect time (how long the users have used the service).  

In Ipsec/L2TP, is there a way to check the users' connect time? 

       ac -  print statistics about users' connect time
DESCRIPTION
       ac prints out a report of connect time (in hours) based on the logins/logouts in the current wtmp file.

e.g.,
`ac -d -p`

outputs:

        meimei                               1.32
        thomas                              23.42
        atao                                0.30
        tom                                  0.61
Jan 24  total       25.66

        thomas                              24.00
        atao                                 0.89
        kate                                 0.06
Jan 25  total       24.95

Thanks 
Peter

**Comment by hwdsl2** [comment]
@peterjpxie Unfortunately there is no easy way to get statistics for IPsec/L2TP. However, you may want to try this script [1] which I had adapted based on [2], but for IPsec/L2TP instead of PPTP. There is NO guarantee at all and use it at your own risk. The usage and example outputs are very similar to [2], please refer to that project's README. A known issue is that the "Remote IP" column does not work.

Before using, you must add a line "debug" to your "/etc/ppp/options.xl2tpd", and run "service xl2tpd restart".

[1] https://gist.github.com/hwdsl2/9a6b89b19f8bf9e62a523345a23ed358
[2] https://github.com/boukeversteegh/pptpd-monitor

**Comment by peterjpxie** [comment]
Hi  Lin Song

[1] link becomes 404 not found. Could you please share it one more time? Thanks

**Comment by hwdsl2** [comment]
Please see [1] for the l2tp-monitor.py.

[1] https://gist.github.com/hwdsl2/855904bfdf0aec6a9cf8d16882acccea

**Comment by peterjpxie** [comment]
Thanks, Song!

Peter
