### ISSUE TITLE
Local DNS with IPSec/L2TP mode ?

### ISSUE THREAD

**Issue by ochbob** [hwdsl2/setup-ipsec-vpn#1074]
Hello :)

I was wondering if there are some news since 2019 about the 'issue' to get a local DNS working when using IPSec/L2TP ?
Like this issue #707 

I know it's been a while, but I recently try again to get it working even if don't use so much IPSec/L2TP (I prefer IKEv2)
I can't figure out why it does not working.

I mean everything works great with public DNS in my options.xl2tpd AND I can join my local service running on my localhost (like apache web server on different vhost, etc...) but when I set my local DNS (pihole) 192.168.1.100 (same as host) it doesn't work, I can join my local services but internet does not work, request don't go to the DNS.

I just want to know if someone encountered the same problem or if finally, it's just a limitation of IPsec/L2TP mode ?

Thank you !

**Comment by hwdsl2** [comment]
@ochbob Hello! I understand that you want to get a local DNS working for IPsec/L2TP mode. According to [1], if the local DNS server is the VPN server itself, setting the `ms-dns` to `192.168.42.1` in `options.xl2tpd` could work. You must restart the `xl2tpd` service after editing this file. Give this a try and let us know if it works.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/661#issuecomment-552295322

**Comment by mehov** [comment]
HI everyone,

I found this because I have pretty much exactly the same issue. My VPN and DNS are on the same VPS. I'm setting up Android for the first time (IPSec Xauth PSK), and the "Always ON" option asks me for the DNS IP, and I'm not sure what value to enter.

- The public IP of my VPS won't work because I blocked any external connections to the DNS port 53
- `192.168.42.1` suggested above doesn't work
- `192.168.43.1` doesn't work either (my VPN clients are being assigned 192.168.43.10+)

Before Android, I've been using this setup with macOS and iOS (Cisco IPSec, IKEv2), and everything worked, as the Apple clients never asked me for the DNS IP and are have somehow been using the VPN server as the DNS server automatically. Disabling the "Always ON" and leaving the DNS IP empty on the Android does not make a difference and the DNS doesn't work (the internet itself does work however, confirmed by visiting https://1.1.1.1/).

Here's my `iptables` which blocks external traffic to my DNS: 

```
root@example:~# iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
f2b-sshd   tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 22
ACCEPT     udp  --  127.0.0.1            0.0.0.0/0            udp dpt:53
ACCEPT     tcp  --  127.0.0.1            0.0.0.0/0            tcp dpt:53
ACCEPT     udp  --  192.168.43.0/24      0.0.0.0/0            udp dpt:53
ACCEPT     tcp  --  192.168.43.0/24      0.0.0.0/0            tcp dpt:53
DROP       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53
DROP       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53
```

Seeing that the only allowed range is `192.168.43.0/24`, the DNS IP must be somewhere in it.

This is not to hijack someone else's thread, but my issue does look similar, in that I'm also looking for a way to explicitly tell my VPN client to use my VPN server as the DNS server.

**Comment by letoams** [comment]
On Wed, 26 Jan 2022, Al wrote:

> I found this because I have pretty much exactly the same issue. My VPN and DNS are on the same VPS. I'm
> setting up Android for the first time (IPSec Xauth PSK), and the "Always ON" option asks me for the DNS IP,
> and I'm not sure what value to enter.
>
>  *  The public IP of my VPS won't work because I blocked any external connections to the DNS port 53
>  *  192.168.42.1 suggested above doesn't work
>  *  192.168.43.1 doesn't work either (my VPN clients are being assigned 192.168.43.10+)
> 
> Before Android, I've been using this setup with macOS and iOS (Cisco IPSec, IKEv2), and everything worked,
> as the Apple clients never asked me for the DNS IP and are have somehow been using the VPN server as the DNS
> server automatically. Disabling the "Always ON" and leaving the DNS IP empty on the Android does not make a
> difference and the DNS doesn't work (the internet itself does work however, confirmed by visiting
> https://1.1.1.1/).

You could assign 1.1.1.1 and then NAT it to 192.168.43.1 ?

Paul

**Comment by mehov** [comment]
> You could assign 1.1.1.1 and then NAT it to 192.168.43.1 ?

I run `dnsmasq` on the same VPS where I run my VPN. All of the requests need to go to it because it performs some custom lookups and blocks before forwarding the request to the upstream.

**Comment by hwdsl2** [comment]
@mehov For IKEv2 and IPsec/XAuth ("Cisco IPsec") modes, the VPN server does not have an internal IP within the `192.168.43.0/24` network. Therefore `192.168.43.1` cannot be used as the DNS server. On the other hand, `192.168.42.1` doesn't work because your VPN clients are not using IPsec/L2TP mode.

For your use case, you may need to specify your server's public IP as the DNS server. To allow this traffic, you may also need to add an ACCEPT rule to the IPTables FORWARD chain. To troubleshoot further, try temporarily removing the DROP rule in the FORWARD chain and see if the DNS works. Be sure to add the DROP rule back after your testing.

**Comment by mehov** [comment]
Found existing documentation with more info at https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic

Will try IPsec/L2TP.

Thank you for your help!

**Comment by hwdsl2** [comment]
@mehov Thanks for the update.
@ochbob For your use case, please also try using `192.168.42.1` as the DNS server, with the IPTables INPUT rule from the previous comment added.
