### ISSUE TITLE
Disconnect and can’t connect again

### ISSUE THREAD

**Issue by yadude87** [hwdsl2/setup-ipsec-vpn#1089]
I have to uninstall and install again to work again I have tried all troubleshooting and also android wouldn’t connect I just wanna be able to make a IPsec or l2tp for android or iPhone on azure also IKEv2 manual setup on my devices

**Comment by hwdsl2** [comment]
@yadude87 Hello! Please provide more details on this issue, including any error(s) in your redacted VPN logs [1]. Did you open UDP ports 500 and 4500 in Azure firewall [2], if applicable?

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status
[2] https://docs.microsoft.com/en-us/azure/firewall/overview

**Comment by yadude87** [comment]
yes both ports are open i used you deploy button

alex@vpnserver:~$ ipsec status
whack: no right to communicate with pluto (access("/run/pluto/pluto.ctl"))
alex@vpnserver:~$ ipsec trafficstatus
whack: no right to communicate with pluto (access("/run/pluto/pluto.ctl"))
alex@vpnserver:~$ sudo ipsec trafficstatus
alex@vpnserver:~$ 
 


[Untitled 2.odt](https://github.com/hwdsl2/setup-ipsec-vpn/files/7964293/Untitled.2.odt)

**Comment by hwdsl2** [comment]
@yadude87 Thanks for the details. I tested using the Azure deploy button in this repository to create a Ubuntu 20.04 VM, then used both iOS 15 and Android 11/12 clients to connect. In my tests, all three modes (IKEv2, IPsec/L2TP and IPsec/XAuth ("Cisco IPsec")) worked fine without issues. In addition, the client devices were able to re-connect without issues after disconnecting. Please note that IKEv2 is not set up by default when using the Azure deploy button, you'll need to log into the VM and set it up using `sudo ikev2.sh --auto`.

Your logs contain "retransmission" errors, which indicate that there are network issues between your VPN client(s) and the VPN server. Sometimes, this could be due to censorship that blocks IPsec VPNs.

Perhaps you can try deploying the VM in a different Azure region closer to you, try a different cloud provider, or switch to an alternative solution that is not IPsec-based.

**Comment by yadude87** [comment]
IKEv2 mobileconfig file works fine but I can’t connect to neither l2tp or IPsec with the username password psk  I used when I deployed the azure vps

**Comment by hwdsl2** [comment]
@yadude87 Please keep using IKEv2 if it works for you, as it is the recommended connection mode. You do need to securely transfer the generated .mobileconfig file to your client device. See [1] for more details.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#configure-ikev2-vpn-clients

**Comment by yadude87** [comment]
i want ipsec and l2pt to connect for android sswan not working on android
