### ISSUE TITLE
iPhone 和Mac 无响应

### ISSUE THREAD

**Issue by zdqxxx124** [hwdsl2/setup-ipsec-vpn#111]
l2tp vpn服务器没有响应。 请尝试重新连接

建立好vpn后第一时间iPhone可以连接。  12小时后iPhone和Macbook 都是这个错误提示

**Comment by peterjpxie** [comment]
Sometimes it is because of the China's network restriction.  I setup a server in Digital Ocean Singapore and it happened now and then on my server while my friends try to connect from China mainland, but it is always working fine while I connect to the server from overseas. 
Have you tried on windows client? Just to see if it is server issue or special client issue.

**Comment by zdqxxx124** [comment]
But the thing is, I'm not use it in China.

**Comment by hwdsl2** [comment]
@zdqxxx124 The iPhone will disconnect its Wi-Fi a few minutes after the
screen goes to sleep. As a result the VPN will be disconnected (because the
Wi-Fi disconnects).

If you turn on the screen again, it will say that the server did not
respond and require a re-connect. According to Apple this is by design (to
save battery) and is normal and expected behavior.

Similarly, the Macbook does not keep Wi-Fi always on after the screen goes
to sleep. So it is normal to see the message you mentioned.

I believe OpenVPN has a feature to auto reconnect after the screen is
turned back on.
