### ISSUE TITLE
the connection is disconnected.

### ISSUE THREAD

**Issue by ylrykurunovadan** [hwdsl2/setup-ipsec-vpn#1114]
**Server
- OS: CentOS 7 [VMWare + CWP]

**Client
- Device: PC & Samsung S20 FE
- OS: Windows 10 & Android 12
- VPN mode: [IPsec/L2TP and IKEv2]

**Additional context**
When I do a speed test, the connection is disconnected.

**Comment by hwdsl2** [comment]
@ylrykurunovadan Hello! The issue you mentioned (disconnected when doing a speed test) is most likely caused by network issues on your VPN server, rather than an issue with IPsec VPN itself. It could be a transient issue, please try again.

**Comment by ylrykurunovadan** [comment]
When I retested it, it turned off again.

**Comment by hwdsl2** [comment]
@ylrykurunovadan Please check the VPN logs for errors:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

**Comment by ylrykurunovadan** [comment]
![image](https://user-images.githubusercontent.com/75165132/156942279-dc51345a-4603-403a-8e23-dd69e83c1bc5.png)
xl2tpd output does not arrive

**Comment by hwdsl2** [comment]
@ylrykurunovadan The `retransmission` errors in your logs indicate that this is most likely caused by network issues on your VPN server. Firstly, please make sure that both UDP port 500 and UDP port 4500 are open on the VPN server or its external firewall (if any).

In addition, make sure that the server address you specify on VPN client devices **exactly match** the server address in the output of the IKEv2 helper script. If you need to change the IKEv2 server address, see [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#change-ikev2-server-address
