### ISSUE TITLE
IKEv2 error Windows 10

### ISSUE THREAD

**Issue by anartikov** [hwdsl2/setup-ipsec-vpn#1115]
**Describe the issue**
Sorry for my english.
I use a translator.
Configured everything as you indicated.
I'm trying to connect - error.
"Cannot connect to vpn. Group Policy mapping error"
I am ready to provide you with any information. Help solve this problem.

**To Reproduce**

1. Create new IKEv2 client config (sudo ikev2.sh)
2. Import P12 Certificate using ikev2_config_import.cmd
3. restart server and Windows
4. Cannot connect to vpn. Group Policy mapping error
5. Edit registry ([download .reg file)
6. Reboot Windows
7. Cannot connect to vpn. Group Policy mapping error

**Logs**
Mar  6 21:08:06 NartServ2 pluto[1639]: packet from 95.165.150.94:294: ISAKMP_v2_IKE_SA_INIT message received on 116.203.181.10:500 but no suitable connection found with IKEv2 policy
Mar  6 21:08:06 NartServ2 pluto[1639]: packet from 95.165.150.94:294: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN

**Server (please complete the following information)**
CentOS Linux release 7.9.2009
Libreswan version is 4.6

**Client (please complete the following information)**
- Device: PC
- OS: Windows 21H2 19044.1566
- VPN mode: IKEv2

**Additional Info
Android 10 connection error too.

**Comment by hwdsl2** [comment]
@anartikov Hello! It looks like you reported the error earlier in #723 and #724. I'm not sure why this error occurs, because IKEv2 is already set up on the VPN server. Try setting the NegotiateDH2048_AES256 in the registry to 1. Run this in an elevated command prompt on your Windows computer:

```
REG ADD HKLM\SYSTEM\CurrentControlSet\Services\RasMan\Parameters /v NegotiateDH2048_AES256 /t REG_DWORD /d 0x1 /f
```

Try re-connecting the VPN. If not working, try setting it to 0:

```
REG ADD HKLM\SYSTEM\CurrentControlSet\Services\RasMan\Parameters /v NegotiateDH2048_AES256 /t REG_DWORD /d 0x0 /f
```

Try re-connecting the VPN. Let us know if these works for you.

Reference:
https://askto.pro/question/how-do-i-fix-the-group-policy-mapping-error

**Comment by anartikov** [comment]
Found an error. More precisely, I did not quite find it. Reinstalled completely VPS from scratch. Everything works fine. Thanks!
