### ISSUE TITLE
IKEV2 username and password only authentication

### ISSUE THREAD

**Issue by amirdana** [hwdsl2/setup-ipsec-vpn#1139]
hi everybody

i was just wondering is there a server configuration that allows users to connect with username and password only (no certificates).
i have problem hosting the files and it would be very neat to use username and pass only.

 thanks for the great job you doing.

**Comment by letoams** [comment]
On Thu, 24 Mar 2022, Amirhosssein Lavasani wrote:

> i was just wondering is there a server configuration that allows users to connect with username and password only (no
> certificates).
> i have problem hosting the files and it would be very neat to use username and pass only.

Not yet. That would create different EAP methods and/or one of the PAKE
methods to be implemented. (eg RFC 6467 https://tools.ietf.org/html/rfc6467)

**Comment by bobbyl140** [comment]
Hey, it's been a while since this issue was updated. [This other project](https://github.com/jawj/IKEv2-setup) uses strongSwan which seems to support this function, obviously this project uses libreswan but it seems to me that it should be possible in libreswan in the end. I know this isn't something that's up to this project to implement until libreswan updates, but I was wondering if anyone can direct me to somewhere I could keep updated on the progress of that. Thanks!

**Comment by lilynet336** [comment]
If anyone else comes across this issue, one can use strongSwan to achieve IKEv2, plain IPsec, and L2TP/IPsec, all with just username+password, and then of course a PSK for IPsec and L2TP modes. 

@amirdana and anyone else reading this, I'm more than happy to provide configs if you still want them!

To the maintainers of this project, I realize libreswan and strongSwan are completely different tools here, albeit for the same job, but I'm willing to help make the switch if it's something you're interested in!

**Comment by paulwouters** [comment]
I am not sure what "IKEv2 username and password only" means. You mean using a PAKE? If so, which one do you mean?

    RFC 6467: Establishes the Secure Password Framework for IKEv2, outlining how peers negotiate PAKE methods during initial exchanges. 
    RFC 6631: Adapts Password Authenticated Connection Establishment (PACE for IKEv2) to convert short passwords into stronger session keys. 
    RFC 6628: Details Efficient Augmented Password-Only Authentication (AugPAKE for IKEv2) to resist active/passive dictionary attacks and server compromise. 

Neither are supported by libreswan. And usually using PAKE still requires a machine certificate for the server auth to the client?
We havent seen any demand for this feature

**Comment by lilynet336** [comment]
I'm not entirely sure which PAKE/PACE method my configuration uses, to be honest I'm not as well-versed in IKE/IPsec as it might seem. I know my way around it but I'm not an expert by any means.

I didn't mention the server authentication in that previous comment, you do still need a server certificate, but the clients don't need machine certificates, only the username/password pair. 

As for demand, it is certainly an uncommon request compared to how many issues have been filed for the project, but when searching all issues matching "password" I found at least this one, #1541, #1220 and #1221 by the same author, #832, and #534, and it would indirectly solve the issue in #1002. 

I see the idea of implementing this as a positive both because it allows one to use consistent user credentials for all three methods of connecting to the server (ignoring the PSK and the server cert for IKEv2 of course). Additionally, it removes the requirement to keep the certificates on-hand, which I personally think makes onboarding a new device significantly easier.

**Comment by lilynet336** [comment]
Oh and my successful configuration was with strongSwan, not libreswan, since libreswan doesn't support EAP methods.
