### ISSUE TITLE
Uninstall script does not remove fail2ban

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#1229]
The uninstall script `wget https://get.vpnsetup.net/unst -O vpnunst.sh && sudo bash vpnunst.sh` does not uninstall and remove fail2ban. If this is done intentionally, can we get some documentation on how to manually remove it?

**Comment by hwdsl2** [comment]
@nodesocket Hello! Thanks for bringing this to my attention. This (not removing fail2ban) was not intentional. However, some users may have fail2ban installed before installing the VPN. In that case, it would be incorrect for the uninstall script to remove fail2ban.

I can update the uninstall documentation with instructions on how to remove fail2ban. The steps would be to first stop the fail2ban service, then remove it using your system's package manager (e.g. apt-get).

**Comment by nodesocket** [comment]
@hwdsl2 ok, so just something like:

```
sudo service fail2ban stop
sudo apt-get remove --purge fail2ban
```

**Comment by hwdsl2** [comment]
@nodesocket The "apt-get" command should probably be `apt-get purge fail2ban`, the rest is correct.
