### ISSUE TITLE
OS detection fails on Azure w/Debian

### ISSUE THREAD

**Issue by GeorgeTsiokos** [hwdsl2/setup-ipsec-vpn#123]
I used the _Deploy to Azure_ button with `Debian` selected but the script failed. I ran the script manually and received the error: `This script only supports Ubuntu/Debian.`. I removed this check and the script ran successfully:
```
if [ "$os_type" != "Ubuntu" ] && [ "$os_type" != "Debian" ] && [ "$os_type" != "Raspbian" ]; then
  exiterr "This script only supports Ubuntu/Debian."
fi
````

**Comment by hwdsl2** [comment]
@GeorgeTsiokos Hello! Thanks for the report. Yes you are correct that if you run the script manually on a Debian 8 VM on Azure, it currently cannot detect the OS due to the missing "lsb_release command".

However, when you use the "Deploy to Azure" button, the install script will check whether "lsb_release" is installed, and will install it as needed. See [1]. Therefore, I think there could be other reasons why that button is not working. Unfortunately I don't have an Azure account to test this.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/azure/install.sh#L6-L11
