### ISSUE TITLE
How to use the x509 certification for ipsec/xauth?

### ISSUE THREAD

**Issue by samuelchchan** [hwdsl2/setup-ipsec-vpn#1233]
Hi, so I want to use x509 certificate for the authentication of Cisco Ipsec so that I can have VPN on demand. How is that going to work? Should I just generate the code directly on the server? Once I have the certificate, is there any particular settings I need to change for the server?

or if there is a chance IKEv2 can have username and password options, as I would like to push the configuration through MDM server.

thank you

**Comment by hwdsl2** [comment]
@samuelchchan Hello! IKEv2 with username and password authentication is not currently available in this project. It is not yet supported in Libreswan 4.7.

Regarding using certificates for authentication in Cisco IPsec mode, this is also not currently available in this project. However, Libreswan does support this. You can follow these examples [1] (in particular, section "Server ipsec.conf for XAUTH/RSA") to add a connection `xauth-rsa` to your server's `/etc/ipsec.conf`. Refer to `/etc/ipsec.d/ikev2.conf` on your server for some of the parameters such as `leftcert` and `leftid`. You may be able to use the same client certificates generated for IKEv2 for the Cisco IPsec authentication.

Remember to restart the IPsec service for the changes to take effect. In case clients connect to IKEv2 instead of Cisco IPsec, you may need to comment out the connection in `/etc/ipsec.d/ikev2.conf`.

[1] https://libreswan.org/wiki/VPN_server_for_remote_clients_using_IKEv1_XAUTH_with_Certificates
