### ISSUE TITLE
ikev2 -Working in one ISP and is not working on another ISP

### ISSUE THREAD

**Issue by hussienalbree** [hwdsl2/setup-ipsec-vpn#1245]
Hi dear, I hope you are doing well, I have my AWS EC2 with an IKEV2 connection between the EC2 and the Mikrotik Router once the WAN connection on specific ISP it's work very great once I connect my Mikrotik with another ISP it's keep disconnect everytime and some time doesn't working at all , please help

**Comment by hwdsl2** [comment]
@hussienalbree Hello! The issue you described is most likely caused by the specific ISP (network issues?), and not an issue with the VPN server itself. You can check logs and VPN status [1] to see if there is any error, and also check the IKEv2 troubleshooting section [2]. Unfortunately, I can't help you troubleshoot further on this issue.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#troubleshooting
