### ISSUE TITLE
error "no proposal chosen"

### ISSUE THREAD

**Issue by bk7473077** [hwdsl2/setup-ipsec-vpn#1256]
Hi,
I have a new server, tried to install IPSec vpn for FritzBox router. With other server it worked without problem (I change to aggr mode and so on on, it worked with other server). On the new one I have an error "no proposal chosen", really don't understand what is it.
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 11]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 15]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**

**Comment by hwdsl2** [comment]
@bk7473077 Hello! To improve security, the VPN scripts were recently updated to disallow the less secure DH group 2 `modp1024` as well as `modp1536`.

If you can, update your FritzBox's configuration to use the more secure `modp2048` or above.

If not, there's another option (not recommended since it's less secure): Edit /etc/ipsec.conf on the VPN server. Find the line `ike=...` and append `,aes256-sha2;modp1024,aes128-sha1;modp1024,aes256-sha2;modp1536,aes128-sha1;modp1536` at the end. Save the file and run `sudo service ipsec restart`. This will re-enable support for these less secure DH groups.
