### ISSUE TITLE
Incorrect PSK and username set on Ubuntu 16.04

### ISSUE THREAD

**Issue by mark-turner** [hwdsl2/setup-ipsec-vpn#130]
Hi,

Thanks so much for this script. It works great but I did spend some time trying to debug why I was getting authentication failures. It turned out that the values I set in the script for PSK and username were not set properly in the resulting config files. Both values were pre-pended with "u2018" and appended with "u2019" in the config files. For example:

My config script settings:
YOUR_IPSEC_PSK=‘hijkr4v2mRNPq3uGq4jsVp9hL’
YOUR_USERNAME=‘myuser’
YOUR_PASSWORD='omgHZ?eg88s'

Resulted in the following config files being generated:

/etc/ipsec.secrets
%any  %any  : PSK "u2018hijkr4v2mRNPq3uGq4jsVp9hLu2019"

 /etc/ppp/chap-secrets.old
'# Secrets for authentication using CHAP
'# client  server  secret  IP addresses
"u2018myuseru2019" l2tpd "omgHZ?eg88s" *

After changing those values and restarting the services, authentication worked and the system is running perfectly. 

BTW, I'm running this on a stock AWS Ubuntu 16.04.2 LTS image, and I pasted my customized script into the "User data" text box when initializing the instance.

Thanks again!

/Mark

**Comment by hwdsl2** [comment]
@mark-turner Hello! Thanks for the report. But this is not a bug in the scripts. The reason that your VPN credentials were pre-pended with "u2018" and appended with "u2019", is because you incorrectly used "curly quotes" `‘’` instead of "straight quotes" `''` for "IPSEC_PSK" and "USERNAME" variables. These "curly quotes", which have unicode U+2018 [1] and U+2019 [2], respectively, are not recognized in shell scripts and should not be used.

In your case, to additionally fix IPsec/XAuth (Cisco IPsec), you may want to correct the username in `/etc/ipsec.d/passwd` as well, then restart IPsec service.

Note: It is recommended that you change your VPN credentials as this issue is posted publicly.

[1] https://unicode-table.com/en/search/?q=U%2B2018
[2] https://unicode-table.com/en/search/?q=U%2B2019

**Comment by mark-turner** [comment]
Hi @hwdsl2 
Thanks for your quick reply. You're right! I see that my text editor replaced the straight quotes with curly ones. They look so similar, I didn't notice before. I will avoid using that editor in the future.
Best regards,
Mark

**Comment by mark-turner** [comment]
P.S. The PSK and password I used in this bug report are not the real ones, but thank you for removing them anyway.
