### ISSUE TITLE
speed limit

### ISSUE THREAD

**Issue by mynewname2020** [hwdsl2/setup-ipsec-vpn#1303]
Using L2TP/IPSEC client on windows server 2022, the downlink speed is limited within 1M, and the uplink speed is normal

**Comment by hwdsl2** [comment]
@mynewname2020 Hello! The bandwidth observed from VPN clients when connected to the VPN is limited by your VPN server's uplink or downlink bandwidth, whichever is lower. This is because VPN traffic generally need to travel through your VPN server to/from your VPN client(s). There is also some overhead due to VPN encryption.

[IKEv2 mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) is recommended over IPsec/L2TP mode, due to the use of AES-GCM ciphers which has [lower overhead](https://libreswan.org/wiki/Benchmarking_and_Performance_testing).

**Comment by horasjey** [comment]
> the downlink speed is limited within 1M

i have same problame sir @hwdsl2 ,

if i use mode ikv2 , l2tp not connceted, 
use  IPsec/L2TP l2tp conected

can help me how to fix?

in my log not show eror

`Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1111]: death_handler: Fatal signal 15 received
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1119]: Stopping xl2tpd: xl2tpd.
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z systemd[1]: xl2tpd.service: Succeeded.
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1141]: Not looking for kernel SAref support.
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1141]: Using l2tp kernel support.
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1124]: Starting xl2tpd: xl2tpd.
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1142]: xl2tpd version xl2tpd-1.3.12 started on iZk1a9mngo5nvc4ykykee8Z PID:1142
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1142]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1142]: Forked by Scott Balmos and David Stipp, (C) 2001
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1142]: Inherited by Jeff McAdams, (C) 2002
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1142]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Jan 25 14:00:05 iZk1a9mngo5nvc4ykykee8Z xl2tpd[1142]: Listening on IP address 0.0.0.0, port 1701`

**Comment by hwdsl2** [comment]
@horasjey Hello! Your logs look normal. IKEv2 mode does not use L2TP, so it is normal that L2TP is not connected in this mode. 

Regarding bandwidth, I would suggest using IKEv2 mode which may have better performance compared to IPsec/L2TP mode. Please also refer to my comment earlier in this issue on bandwidth and VPN encryption overhead.
