### ISSUE TITLE
establishing connection 'myvpn' failed

### ISSUE THREAD

**Issue by Feng573795502** [hwdsl2/setup-ipsec-vpn#1324]
`root@snail:/home/snail# ipsec restart
Stopping strongSwan IPsec...
Starting strongSwan 5.6.2 IPsec [starter]...
root@snail:/home/snail# ipsec up myvpn
initiating Main Mode IKE_SA myvpn[1] to 192.168.8.129
generating ID_PROT request 0 [ SA V V V V V ]
sending packet: from 192.168.8.120[500] to 192.168.8.129[500] (240 bytes)
received packet: from 192.168.8.129[500] to 192.168.8.120[500] (144 bytes)
parsed ID_PROT response 0 [ SA V V V ]
received FRAGMENTATION vendor ID
received DPD vendor ID
received NAT-T (RFC 3947) vendor ID
generating ID_PROT request 0 [ KE No NAT-D NAT-D ]
sending packet: from 192.168.8.120[500] to 192.168.8.129[500] (372 bytes)
received packet: from 192.168.8.129[500] to 192.168.8.120[500] (372 bytes)
parsed ID_PROT response 0 [ KE No NAT-D NAT-D ]
local host is behind NAT, sending keep alives
remote host is behind NAT
generating ID_PROT request 0 [ ID HASH N(INITIAL_CONTACT) ]
sending packet: from 192.168.8.120[4500] to 192.168.8.129[4500] (108 bytes)
received packet: from 192.168.8.129[4500] to 192.168.8.120[4500] (76 bytes)
parsed ID_PROT response 0 [ ID HASH ]
IDir '112.96.230.108' does not match to '192.168.8.129'
deleting IKE_SA myvpn[1] between 192.168.8.120[192.168.8.120]...192.168.8.129[%any]
sending DELETE for IKE_SA myvpn[1]
generating INFORMATIONAL_V1 request 1729082173 [ HASH D ]
sending packet: from 192.168.8.120[4500] to 192.168.8.129[4500] (92 bytes)
establishing connection 'myvpn' failed
`
`
# ipsec.conf - strongSwan IPsec configuration file

conn myvpn
  auto=add
  keyexchange=ikev1
  authby=secret
  type=tunnel
  left=%defaultroute
  leftauth=psk
  leftprotoport=17/1701
  rightprotoport=17/1701
  right=192.168.8.129
  ike=aes128-sha1-modp2048
  esp=aes128-sha1
  rightauth=psk
`
Unable to connect in LAN

![image](https://user-images.githubusercontent.com/22174575/218318434-ee79a2bb-33fc-42e4-b836-06cafbe918ba.png)

**Comment by hwdsl2** [comment]
@Feng573795502 Hello! It looks like you are trying to connect to the VPN server's private IP address `192.168.8.129`, instead of its public IP `112.96.X.X`. For this use case, please try the following fixes:

1. Edit `ipsec.conf` on your VPN client (NOT server). Add the line `rightid=112.96.X.X` after the line `right=...`. Replace the IP with your server's actual public IP address. Then save the file and restart the connection on the VPN client.
2. If (1) does not work, try editing `/etc/ipsec.conf` on the VPN server. Find the line `leftid=...` and replace it with your server's private IP `192.168.8.129`. Save the file and run `sudo service ipsec restart`.
