### ISSUE TITLE
[RFE] Modify IKEv2 tutorial to add existing LE certificates instead of building self-signed.

### ISSUE THREAD

**Issue by keijodputt** [hwdsl2/setup-ipsec-vpn#133]
**This is a Request For Enhancement (RFE):**

My VPN host is capable of using Letsencrypt ([now EFF certbot](https://certbot.eff.org/))(1) generated certificates to identify itself gracefully. This is a great advantage when providing a certificate from a trusted CA over a self-signed, I think. Is there a chance this can be also covered in the [ikev2-howto](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md)(2) tutorial?
I'm following this other tuto ([based on StrongSwan](https://hub.zhovner.com/geek/universal-ikev2-server-configuration/))(3) but it would be like _totally-awesome-dude-hellyeah_ to have it all in here.

Thanks in advance.
Keijo!

Refs:
(1)[https://certbot.eff.org/](https://certbot.eff.org/)
(2)[https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md)
(3)[https://hub.zhovner.com/geek/universal-ikev2-server-configuration/](https://hub.zhovner.com/geek/universal-ikev2-server-configuration/)

**Comment by hwdsl2** [comment]
Not sure how to accomplish this... Pull requests welcome.   
For now please continue to follow the other tutorial you mentioned.

**Comment by hwdsl2** [comment]
Thanks to @keijodputt for the suggestion. However, I am closing this issue because:

1. For IKEv2, unlike strongSwan, Libreswan only supports authentication using machine certificates, not username/password combinations. Therefore, the configuration referenced in the OP's tutorial is not really applicable to Libreswan.

2. For authentication with machine certificates, a certificate import operation would be required on the VPN client anyway, regardless of whether a self-signed CA is used. 

3. Also, the 90-day short validity period of Letsencrypt certificates could reduces its usability in such use cases.
