### ISSUE TITLE
You can not connect from two different devices (one ip)

### ISSUE THREAD

**Issue by bubnivevg** [hwdsl2/setup-ipsec-vpn#1345]
Hello. Can you please tell me how to fix this problem?

The situation is as follows. My wife and I use your development and our VPN works great. We connect to the VPN through our iPhones, and use the same wifi network. I noticed such a problem that we cannot simultaneously sit in the Instagram application (possibly in others at the same time), it only works for one person. At the same time, the simultaneous use of different sites or applications works fine. The problem only occurs when we use the same application at the same time. At the same time, if I switch to mobile Internet and connect VPN, and she continues to use Wi-Fi with VPN connected, then everything works fine.
I tried to solve the problem, looked through the config files and didn't find anything. Help me to understand! Thank you.

**Comment by hwdsl2** [comment]
@bubnivevg Hello! The issue you described is most likely with the particular application you mentioned, and not an issue with the VPN server itself. For the VPN, I assume that you already use the recommended [IKEv2 mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) to connect, instead of IPsec/L2TP mode. If not, please give it a try.
