### ISSUE TITLE
2 simultaneous connections

### ISSUE THREAD

**Issue by alexpotbitweb** [hwdsl2/setup-ipsec-vpn#1367]
Hello! Thank you for the work done, the script really simplifies the work and launch of servers. I have a problem that I don't know how to solve. The situation is as follows

1. I create 2 accounts through the ikev2.sh script
2. I import the received profiles into android and into windows pc
3. I try to connect, the connection occurs on both devices
4. but data exchange (opening sites, etc.) occurs only on the device that connected last.

Server OS Centos 7
Android 13 client - strongswan
Windows 10 client - native (im using ikev2_config_import.cmd)

+ I tried to connect with android and windows pc both on the same network and on different ones - the situation does not change

please help with a solution

**Comment by hwdsl2** [comment]
@alexpotbitweb Hello! The issue you described is probably because the second connection replaced the first one. This normally should not happen unless you are using the same IKEv2 certificate on both clients.

First make sure that the IKEv2 profiles you imported to Android and Windows contain unique certificates. It looks like you already done this step but please double check. Create a new IKEv2 client and import again if you are unsure.

Also check and make sure your /etc/ipsec.conf contains uniqueids=no. This is the default config in the scripts.

Restart the IPsec service using "sudo service ipsec restart".

You can also try switching the order of connection for Android and Windows.
