### ISSUE TITLE
change-ikev2-server-address: I cannot enter new pub_ip address

### ISSUE THREAD

**Issue by mariano-daniel** [hwdsl2/setup-ipsec-vpn#1369]
So, I'm following instructions as per [change-ikev2-server-address](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#change-ikev2-server-address) since my pub_ip on the IKEV2 server changed, however I am asked to enter the FQDN, when originally when I ran the [setup-ipsec-vpn](https://github.com/hwdsl2/setup-ipsec-vpn) script, it simply took my pub_ip address without asking for a FQDN.

How can I redo my server ip_address without a FQDN?

Thanks!

**Comment by hwdsl2** [comment]
@mariano-daniel Hello! The "change IKEv2 server address" script does allow specifying a new IP address instead of a DNS name (FQDN). Follow the [instructions](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#change-ikev2-server-address) to run the script, it will first ask:
```
Do you want IKEv2 VPN clients to connect to this server using a DNS name,
e.g. vpn.example.com, instead of its IP address? [y/N]
```
If you answer "N" at this point, the script will then ask for your server's IP address:
```
Enter the IPv4 address of this VPN server:
```
Enter your server's new IP at this point. If this still doesn't work, let us know.
