### ISSUE TITLE
Only allowing one Chromebook to connect on each network.

### ISSUE THREAD

**Issue by bignate26** [hwdsl2/setup-ipsec-vpn#1386]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ... create two ip sec users
2. ... try to connect two Chromebooks to the same server on the same network.

**Expected behavior**
The second chromebook will not connect.

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 11] ubuntu
- Hosting provider (if applicable): [e.g. GCP, AWS] vultr

**Client (please complete the following information)**
- Device: [e.g. iPhone 12] 2 Hp Chomebooks 
- OS: [e.g. iOS 15] chomeos 
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2] Ipsec/2tp

**Additional context**

**Comment by hwdsl2** [comment]
@bignate26 Hello! As mentioned in the [important notes](https://github.com/hwdsl2/setup-ipsec-vpn#important-notes), due to an IPsec/L2TP limitation, if you wish to connect multiple devices from behind the same NAT (e.g. home router), you must use [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) or [IPsec/XAuth](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md) mode.

For Chrome OS, see [IKEv2 configuration instructions](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#chrome-os). Make sure to [generate a unique IKEv2 client certificate](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#manage-ikev2-clients) for each client.
