### ISSUE TITLE
Windows VPN error connection

### ISSUE THREAD

**Issue by carlos-gomez-espinosa** [hwdsl2/setup-ipsec-vpn#1407]
Hi, I have had the IKEv2 VPN configured for several devices for months now. 
It has been working perfect, and from iOS it works perfect both IKEv2 and L2TP.
However from Windows I get IKE authentication credentials are unacceptable error.

I have checked the DNS and they are correct, in fact I have the same certificate on both iOS and Windows. 
What could be happening?

Thanks in advance

**Comment by hwdsl2** [comment]
@carlos-gomez-espinosa Hello! For the error you mentioned, please refer to [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ike-authentication-credentials-are-unacceptable).

Possible reasons:
1. The IKEv2 connection you added on Windows has your server's IP address as the "server name or address", instead of your server's DNS name. To fix, edit the VPN connection's properties and replace the IP address with your server's DNS name.
2. Alternatively, you may have specified a DNS name as the server address in the IKEv2 connection on Windows, but you did not specify the DNS name when setting up IKEv2. In that case, follow instructions in the link above to change the IKEv2 server address to your desired DNS name.
