### ISSUE TITLE
Client to Client Connection not working

### ISSUE THREAD

**Issue by DressyLemon** [hwdsl2/setup-ipsec-vpn#1416]
**Checklist**

- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
When trying to ping or access other related hosted services on other clients. it is not accessible nor pingble.

**To Reproduce**

Ubuntu Server 1 -> VPN Server

3x Users:
VPN1
VPN2 
VPN3

MikroTik RouterOS -> VPN1
Ubuntu Server 2 -> VPN2
Windows Client -> VPN3

All clients are fully capable of pinging the VPN Server. Although Clients cannot ping each-other.

**Expected behavior**
Clients can ping each-other

**Server (please complete the following information)**
- OS: Ubuntu Server LTS ( Latest ) 
- Hosting provider (if applicable): FastHosts

**Client (please complete the following information)**
- VPN mode: IPsec/L2TP

**Additional context**
Followed advice mentioned previously but sadly still can't get this to work.

**Comment by hwdsl2** [comment]
@DressyLemon Hello! Client-to-client traffic is enabled by default. If connected VPN clients cannot reach each other, it is usually because the firewall on each client is blocking such traffic.

You can test by temporarily removing the last DROP rule from the IPTables FORWARD chain on the VPN server, which will allow all forwarded traffic. Then try the client to client traffic again. Be sure to add the rule back after testing.

**Comment by hwdsl2** [comment]
@DressyLemon If you have tested that temporarily removing the DROP rule doesn't work, the issue is not on the VPN server side. Check that you are using the correct internal IPs for traffic between VPN clients. Refer to the link in my previous reply.

**Comment by hwdsl2** [comment]
@DressyLemon Yes, on the VPN server you can temporarily remove the last DROP rule from the IPTables FORWARD chain to test. Make sure that you add the rule back after testing for security. If client-to-client traffic still doesn't work after removing the DROP rule, then the issue is not on the VPN server side.

**Comment by wolasss** [comment]
I am facing the same issue lately on Ubuntu 20.04.6 LTS, I noticed that iptables rules are not added at all on startup (with --network host and --priveledged)
