### ISSUE TITLE
Управление клиентами

### ISSUE THREAD

**Issue by aleksan149** [hwdsl2/setup-ipsec-vpn#1431]
Возможно ли отозвать сертификат клиента, а потом возобновить его действие прямо на сервере, не устанавливая новый сертификат для клиента? Или есть другой способ управлять подписками для клиентов?

**Comment by hwdsl2** [comment]
@aleksan149 Hello! This feature is not supported. If a client certificate expires, you will need to generate a new client certificate on the server using the "add a new client" option of the IKEv2 script, then import the new profile into the VPN client and remove the existing profile. This is required due to expiration of the existing certificate on the client.
