### ISSUE TITLE
Always On VPN for Android native IKEv2 client

### ISSUE THREAD

**Issue by mrbluecoat** [hwdsl2/setup-ipsec-vpn#1437]
Your https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md guide indicates `(Optional feature) You can choose to enable the "Always-on VPN" feature on Android. Launch the Settings app, go to Network & internet -> Advanced -> VPN, click the gear icon on the right of "strongSwan VPN Client", then enable the Always-on VPN and Block connections without VPN options.`

However, your video guide for the native Android 11+ IKEv2 client says "The information provided doesn't support always-on VPN"

![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/382164/f77d064d-ab3a-4e39-abca-05461db140cf)

Is Android IKEv2 always-on VPN only supported with the strongSwan app and not the native client?

**Comment by hwdsl2** [comment]
@mrbluecoat Hello! For the Android IKEv2 always-on VPN feature, please use it with the strongSwan VPN client app.

For the native IKEv2 client in Android, there are certain requirements for the always-on VPN option to be available. For example, the VPN server address should be an IP address instead of a DNS (domain) name. I am not sure about the exact requirements though.
