### ISSUE TITLE
Script + Virtualmin not get

### ISSUE THREAD

**Issue by Svrbinek** [hwdsl2/setup-ipsec-vpn#1451]
Hello,
I am no programming and IT professional. But I tried this script on debian 9 and it worked with virtualmin. However, I had to upgrade to debian 12 and here is the problem. After installing Virtualmin and then installing the vpn script, the vpn no longer communicates with the home router as a client. Because I don't understand it, I don't know where the problem is. But when installing the script itself without Virtualmin, the script works. This means that there is a conflict somewhere. Can you verify this please?

**Comment by hwdsl2** [comment]
@Svrbinek Hello! This issue could be caused by IPTables rules incompatibilities between the IPsec VPN and Virtualmin. You can check the current IPTables rules using:

sudo iptables -nvL; sudo iptables -nvL -t nat

Unfortunately I am not familiar with Virtualmin and cannot help you troubleshoot further. I would suggest that you set up the VPN on a new server without Virtualmin.
