### ISSUE TITLE
Перестал подключаться vpn из на android, и на iOS

### ISSUE THREAD

**Issue by Valentine13** [hwdsl2/setup-ipsec-vpn#1455]
Установила по инструкции на свой vps ваш vpn где-то полгода назад, и до недавнего времени всё работало отлично, но где-то с четверга-пятницы я не могу подключиться. Провайдер (time4vps) утверждает, что с его стороны проблем нет. strongswan на android выдает такой лог: см. приложение. Что можно сделать, чтобы все заработало? Спасибо.
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/19172874/b3568427-f3d2-4a4d-b2a5-93e506b444dd)

**Comment by hwdsl2** [comment]
@Valentine13 Hello! Your logs show that the client sent the connection requests, but the VPN server did not complete the connection. A few things to try:

1. There is network issues between the VPN client and server. For example, certain countries might block IPsec VPN connections. In this case, try alternative solutions other than IPsec VPN.

2. Try restarting the IPsec service on the server using: sudo service ipsec restart

3. Try setting up the VPN on a new server instead of the current one.
