### ISSUE TITLE
Lose internet connection

### ISSUE THREAD

**Issue by st-small** [hwdsl2/setup-ipsec-vpn#1494]
Hi! 
Thank you very much for your script and support. I'm using your on my server for a long time and all works always as a clock. But now I have troubles.
My vps provider is Digital ocean.
I have certificates on my iOS and MacOS devices.

Sometimes I get error 'No internet connection' when my vpn connection is on. But if I make it off all works as usual. What I should to do to find a problem and check it? Maybe logs from vps or somewhere else?

Thank for help.

**Comment by hwdsl2** [comment]
@st-small Hello! Please [check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status) for errors. Also see [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting), including the section about macOS Sonoma.

If the issue only happens sometimes, it could be due to network issues between the VPN client and server. Try setting up the VPN on a new VPS can sometimes help.
