### ISSUE TITLE
IPsec/L2TP isn't connecting

### ISSUE THREAD

**Issue by ibrahem2345** [hwdsl2/setup-ipsec-vpn#1518]
### i have a VPS with this spec : 

**1. HDD 5000 Mb
2. OS ubuntu 20.04
3. RAM 512 Mb** 

i bought from this site [https://justhost.ru/en](url) and it's on Frankfurt Germany.
i have installed everything correctly and I'm sure there is wrong with the Script because no connection is established i have tried my laptop WIN 11 , and my home router , and my Android phone and it wouldn't connect , 
can you help me out to fix this problem ? 
### On my laptop it gives this error : 
Error 809: The network connection between your computer and the VPN server could not be established because the remote server is not responding. This could be because one of the network devices (e.g, firewalls, NAT, routers, etc) between your computer and the remote server is not configured to allow VPN connections. Please contact your Administrator or your service provider to determine which device may be causing the problem.
### and i have seen the fix for this problem with the one time registry but it didn't work .
i really wish you could help me to do this ❤️

**Comment by hwdsl2** [comment]
@ibrahem2345 Hello! Please try [IKEv2 mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) instead of IPsec/L2TP. If your VPS has an external firewall (only some providers have that), open UDP ports 500 and 4500 for the VPN.

Note that IPsec VPNs are more easily blocked compared to other solutions such as Shadowsocks. You may want to look into alternative solutions other than IPsec VPN, if it doesn't work for your use case.

**Comment by ibrahem2345** [comment]
### i have opened the ports and still nothing is working .
and i have upgraded Liberswan and all the packages before the installation 😞 .
do you think that the problem is caused from the Provider ?
if it's so can you recommend some providers for me ? 
and thanks a lot ❤️

**Comment by ibrahem2345** [comment]
and i have tried on another VPS provider but still not working and i get the IPsec /  IKEv2 information from the terminal after the installation .
