### ISSUE TITLE
how to config to xauth mode in ubuntu

### ISSUE THREAD

**Issue by chunnallu** [hwdsl2/setup-ipsec-vpn#152]
i had set up the IPSec VPN on ubuntu（in a NAT network） according to the tutorial，but it works only when there has one machine in connetced . So i need a tutorial to tell me how to config the vpn to xauth mode on ubuntu linux，but where can i find the tutorial ?

Chinese：
我已经按照教程再ubuntu上搭建好了IPSec VPN，使用的是NAT网络，所以同一时间只能有一台服务器连上vpn。看教程说是可以使用xauth模式解决这个问题，但是官方给出的[xauth教程](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md)里并没有linux下配置的教程，那在linux下该如何配置成xauth模式呢？

**Comment by hwdsl2** [comment]
@chunnallu Hello! On Ubuntu Linux you can try using "vpnc" to connect to the VPN server via IPsec/XAuth. However, because vpnc only supports IPsec "aggressive mode", it is not compatible with the default configuration set up by the VPN scripts, which supports IPsec "main mode" only. You must manually edit `/etc/ipsec.conf` to make it work. You can find more details at [1] and [2]. Please read all comments in these issues. Note that if you make these changes, when connecting using non-Linux clients, you must provide the group name as well.

[1] #121 
[2] #70

**Comment by chunnallu** [comment]
thanks for reply ! I had look through thoese issues,and now i can login successful on two machine at the same time .But , a new problem appeared, that both of machines can login , but only one can ping google ! 
besides，both of machine are in a LAN network , so , Is it possible to share this vpn in LAN network by many machine? 

my /etc/ipsec.conf file：
```
 conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns1=8.8.8.8
  modecfgdns2=8.8.4.4
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes

  rightid=@[mygroup1]
  aggrmode=yes

  also=shared
```

thanks very much!

**Comment by chunnallu** [comment]
@hwdsl2

**Comment by hwdsl2** [comment]
@chunnallu This behavior could be caused by the same group name used on both of your VPN clients. Try adding another section to your `/etc/ipsec.conf`, but change the `rightid` to something else. For example:

```
conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns1=8.8.8.8
  modecfgdns2=8.8.4.4
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  rightid=@[mygroup1]
  aggrmode=yes
  also=shared

conn xauth-psk-2
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns1=8.8.8.8
  modecfgdns2=8.8.4.4
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  rightid=@[mygroup2]
  aggrmode=yes
  also=shared
```

Save the file and run `service ipsec restart`. Then connect your Linux VPN clients, with one client using `mygroup1`, and the other using `mygroup2`.
