### ISSUE TITLE
Increase maximum no of simultansous connections using same ikev2 file

### ISSUE THREAD

**Issue by saadabbasi9d** [hwdsl2/setup-ipsec-vpn#1543]
How to increase maximum no of simultansous connections using same ikev2 file. Is it good to use same file for multiple users . where should i set this limit or change it .

**Comment by hwdsl2** [comment]
@saadabbasi9d Hello! For VPN clients behind the same NAT (e.g. home router), it is recommended to [create a unique IKEv2 certificate](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#manage-ikev2-clients) for each client device. Otherwise, clients may not be able to connect simultaneously. It is not currently supported to increase the number of simultaneous connections using the same IKEv2 certificate, for devices behind the same NAT.

**Comment by saadabbasi9d** [comment]
What if the NAT is different. Can same config file work for that ? and what is the limit for simultaneous connections using same config file .Thankyou

**Comment by hwdsl2** [comment]
@saadabbasi9d For devices not behind the same NAT, using the same IKEv2 certificate would usually work, and there is no limit in the configuration. However, it is still recommended to generate a unique IKEv2 certificate for each device for this use case.

**Comment by saadabbasi263** [comment]
The Ipses Configuration i.e Username ,password and PSK . Is this Ipsec Only protocol or it's combination of Ipsec & Ikev2 protocols. Thanks For Previous responses as it helped me alot .

**Comment by hwdsl2** [comment]
@saadabbasi263 The IPsec/L2TP and IPsec/XAuth ("Cisco IPsec") modes, which use a combination of username, password and pre-shared key (PSK), are both IKEv1 protocols. [Internet Key Exchange](https://en.wikipedia.org/wiki/Internet_Key_Exchange) (IKE, versioned as IKEv1 and IKEv2) is the protocol used to set up a security association (SA) in IPsec. In this project, IKEv2 mode uses certificate-based authentication.
