### ISSUE TITLE
ipsec.conf obsolete keyword dpdaction and fail2ban conf warning

### ISSUE THREAD

**Issue by phant** [hwdsl2/setup-ipsec-vpn#1560]
**Checklist**

- [+] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [+] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [+] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [+] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [+] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [+] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/805222/de240903-179d-48b9-9d12-65ceea9eda62)

**Is your enhancement request related to a problem? Please describe.**

in `mcedit /etc/ipsec.conf` remove `dpdaction=clear`
in `/etc/fail2ban/fail2ban.conf` uncomment `allowipv6 = auto`

**Comment by hwdsl2** [comment]
@phant Hello! Thank you for your suggestions. For `dpdaction=clear`, because this project was recently updated to use Libreswan 5.0 (from 4.15), that option is kept in the configuration for backwards compatibility with the 4.15 version (for example, users may choose to downgrade to 4.15). It may be removed in a future update in this project.

For `allowipv6 = auto`, this is a [new option](https://github.com/fail2ban/fail2ban/blob/1.0.2/ChangeLog) in Fail2Ban 1.0. Because this project supports a wide range of Linux distributions, some may come with an older Fail2Ban version that does not support this option. See packages for [Debian](https://packages.debian.org/search?keywords=fail2ban) and [Ubuntu](https://packages.ubuntu.com/search?keywords=fail2ban), for example.
