### ISSUE TITLE
Verifying server authentication failed

### ISSUE THREAD

**Issue by bl4ze1g** [hwdsl2/setup-ipsec-vpn#1615]
I set this up a month or so ago and everything worked fine but today, when trying to connect to my Server through Strongswan on Android, I got an error saying Failed to establish VPN: Verifying server authentication failed. I checked and I could still connect to the VPN on my Linux PC so I figured something must be wrong with the config files and went ahead to uninstall and reinstall the whole thing with sudo ikev2.sh --removeikev2 and sudo ikev2.sh --auto
However, after creating a new client with sudo ikev2.sh and exporting the client.sswan file, I could still import it on my phone and create a Certificate for it but it still gives me the same error. Here's the logs from Strongswan (I hope I don't dox myself with this one):
https://paste.ivr.fi/quwuhojefi.apache
Any help much appreciated, please let me know where to find any other relevant logs if needed

**Comment by hwdsl2** [comment]
@bl4ze1g Hello! From your logs there are errors like `no issuer certificate found for "CN=[server IP], O=IKEv2 VPN"`. This could indicate that the IKEv2 VPN CA certificate is not imported correctly on your VPN client device.

To resolve this issue, on your Android device, launch the Settings application, then go to Security -> Advanced -> Encryption & credentials. Select the option to view existing certificates, then remove the certificates related to the IKEv2 VPN. After that, run `sudo ikev2.sh` on your server and select the option to re-export the IKEv2 config for the client. This should output a `.sswan` file which you can re-import to the strongSwan VPN client.

Note that after re-installing IKEv2, it will generate a new IKEv2 VPN CA certificate, that's why you need to remove the existing one from the client and re-import using the steps above.

**Comment by bl4ze1g** [comment]
i did all that yet the issue persists. even tried reinstalling the app and doing all the other steps. here's the strongswan log if it's even any different this time: https://paste.ivr.fi/gabuxihoqi.apache

**Comment by bl4ze1g** [comment]
could someone help me please?

**Comment by hwdsl2** [comment]
@bl4ze1g Hello! Your earlier logs show that the IKEv2 VPN CA certificate is not imported correctly on your Android device. As I said above, you may want to remove the certificates related to IKEv2 VPN on your Android device, delete existing connections inside strongSwan VPN client, then re-export the client configuration and import to the client.
