### ISSUE TITLE
docker for raspberry pi

### ISSUE THREAD

**Issue by leslie-wang** [hwdsl2/setup-ipsec-vpn#170]
Current docker image is based from x86 instruction set. I want to run the docker container on raspberry pi. I created one repo https://github.com/leslie-wang/docker-ipsec-vpn-server-pi. please let me know if you want to merge into your repo, since you are the original author. :-)

**Comment by hwdsl2** [comment]
@leslie-wang Hello! Thanks for sharing your enhancements with us. I prefer not to merge it at this time, because the original project (without docker) can already be used directly on a Raspberry Pi [1].

[1] https://blog.elasticbyte.net/setting-up-a-native-cisco-ipsec-vpn-server-using-a-raspberry-pi/

**Comment by leslie-wang** [comment]
That link works because it uses your native setup script, but not docker one. Dockerfile need be based FROM resin/rpi-raspbian, not FROM debian:jessie for Raspberry PI.
