### ISSUE TITLE
why its slow ?

### ISSUE THREAD

**Issue by 8lbiasian** [hwdsl2/setup-ipsec-vpn#194]
i want to know is it normal that ipsec is slow ? 
even the connecting time its taking like 1 to 2min just to connect 
and most app lagging some times its show me not connecting to internet cant use voip apps
browser is working fine can unblock websites but also slow 

in the other hand same server i use on pptp is working super fast !! 

iam using digitalocean as server for my vpn

**Comment by hwdsl2** [comment]
@8lbiasian Hello! Although IPsec has some overhead due to encryption and encapsulation, what you described is not normal. This is typically due to network issues between your VPN client(s) and the server. Please try the following:

1. Set up the VPN server on another new DigitalOcean droplet in either the same or a different region. Then try again with the new server.
2. Connect to the VPN server using another VPN client (e.g. Windows, Android, iOS), connect using a different method (IPsec/L2TP or Cisco IPsec), or connect from a different network location (e.g. Wi-Fi, 3G).

Closing as this is not an issue with the VPN script itself.
