### ISSUE TITLE
Force all connections through OpenDNS servers

### ISSUE THREAD

**Issue by m0lmk** [hwdsl2/setup-ipsec-vpn#212]
Is there a way to force all clients to use the OpenDNS servers at 208.67.222.222 and 208.67.220.220?

**Comment by unzagi** [comment]
Klxppp00ppp

On 15 Sep 2017 08:14, "Matt" <notifications@github.com> wrote:

Is there a way to force all clients to use the OpenDNS servers at
208.67.222.222 and 208.67.220.220?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hwdsl2/setup-ipsec-vpn/issues/212>, or mute the thread

**Comment by hwdsl2** [comment]
@m0lmk For how to specify DNS servers for VPN clients, please refer to the "important notes" section [1] of the README.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by m0lmk** [comment]
Perfec. Thanks 👍
