### ISSUE TITLE
Dynamic IP address problem.

### ISSUE THREAD

**Issue by Tokyo35123** [hwdsl2/setup-ipsec-vpn#213]
Hello, I setup l2tp ipsec from home and I use it when I travel oversea. Sometime when connection drops or blackout. Ip will be changed. And I have to reinstall vmware and everything. Is there a way to fix this because my isp does not offer static ip address. 

Thank you!!!

**Comment by hwdsl2** [comment]
@Tokyo35123 Hello! The latest version of VPN scripts are already designed in a way that your VPN server should continue to work after its public IP changes. There is no need to reinstall vmware. Try restarting the VM if needed.

(Outside the scope of this project) In order to know your public IP after it changes, you can use a dynamic IP provider such as Dyn or No-IP, combined with the corresponding desktop update client. Then you can use your dynamic DNS hostname to connect to the VPN server.
