### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by biocoderh** [hwdsl2/setup-ipsec-vpn#217]
Clean installed ubuntu on DigitalOcean, but can't connect
Linux ubuntu-512mb-fra1-01 4.4.0-93-generic #116-Ubuntu

pluto[3213]: "l2tp-psk"[1] **.***.73.249 #21: responding to Main Mode from unknown peer **.***.73.249
pluto[3213]: "l2tp-psk"[1] **.***.73.249 #21: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
pluto[3213]: "l2tp-psk"[1] **.***.73.249 #21: STATE_MAIN_R1: sent MR1, expecting MI2
pluto[3213]: "l2tp-psk"[1] **.***.73.249 #21: ERROR: asynchronous network error report on eth0 (sport=500) for message to **.***.73.249 port 500, complainant **.***.73.249: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]

**Comment by hwdsl2** [comment]
@biocoderh Hello! This error is typically caused by mismatched (incorrect) IPsec PSK, or network connection (NAT) issues. Refer to the troubleshooting steps [1]. In addition, make sure that your home router has IPsec passthrough enabled in the settings.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
