### ISSUE TITLE
Ability to pick IP

### ISSUE THREAD

**Issue by Fastidious** [hwdsl2/setup-ipsec-vpn#219]
Will it be possible to add the configurable settings (like user, password, shared key), so a different range of private IPs can be used (like 10.XXX.XXX.XXX, for example)? Thanks!

**Comment by hwdsl2** [comment]
@Fastidious Hello! The internal VPN IP ranges (for all users) can be configured by editing the script. See [1]. However, it is not possible to assign different VPN IP ranges based on username or PSK.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L208-L212

**Comment by Fastidious** [comment]
I understand, I saw it too. Yet, how about:
 `virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!$L2TP_NET,%v4:!$XAUTH_NET`

What I was asking was, to make it simpler, by defining those variables at the top.

**Comment by hwdsl2** [comment]
@Fastidious The line you referred to is usually set to all the RFC-1918 address space in order to exclude the VPN internal IP ranges, as well as those used in the local subnet behind the NAT. See [1] (search for "virtual-private"). Therefore, it is not necessary to define it at the top.

[1] https://libreswan.org/man/ipsec.conf.5.html
