### ISSUE TITLE
Question: only send WLAN traffic to VPN

### ISSUE THREAD

**Issue by DiederikvandenB** [hwdsl2/setup-ipsec-vpn#225]
Hi there. Firstly, thanks for your time and effort! I have used your instructions and it made my life much easier :).

I do have a question though. For my RP3 I followed [these](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux) instructions to connect to my VPN server. Is it possible though to only send the WLAN traffic to the VPN? More details about my question can be found [here](https://serverfault.com/questions/875938/only-route-wlan-over-vpn).

Thanks in advance :)

**Comment by hwdsl2** [comment]
@DiederikvandenB Hello! Unfortunately there is no easy way to achieve what you want ("only send the WLAN traffic to the VPN"), because routing in most OS is only dependent upon the destination address, not the interface used. Here are some references:

[1] https://superuser.com/questions/983727/route-only-specific-traffic-through-vpn
[2] https://www.thomas-krenn.com/en/wiki/Two_Default_Gateways_on_One_System
[3] https://kindlund.wordpress.com/2007/11/19/configuring-multiple-default-routes-in-linux/
