### ISSUE TITLE
L2TP connections disconnect after one hour

### ISSUE THREAD

**Issue by pluush** [hwdsl2/setup-ipsec-vpn#228]
Tried on iOS and Windows. After around one hour, first it will stop all traffic while remaining connected for around one minute and then it disconnects. It seemed like the CHILD_SA rekeying didn't work. IPSec connections are fine after the one-hour mark. Server-side tried on Debian and CentOS, same results. Libreswan is updated to latest at 3.21. Tried on lots and lots of VPSes, same results. I have tried playing with rekey, ikelifetime, lifetime, and others. Putting a lifetime below one hour (ex. 10min) disconnects the client after the specified lifetime (ex. 10min), but not specifying (default script configuration) and putting it above 1h will still disconnect the client after 1hour. Did I miss something?

**Comment by hwdsl2** [comment]
@pluush Hello! Thanks for the report. Because the VPN setup script is a wrapper script for Libreswan (and xl2tpd), you may want to instead opening an issue in the Libreswan repo [1] with the details of your problem and attach all relevant logs, or you may email the Libreswan mailing list [2]. The Libreswan developers usually respond pretty quickly to bug reports. In addition, clicking on the "Swan Archives" link on that page will take you to a list of previous messages where you can look up similar questions by others.

I am closing the issue here since it looks like a bug in Libreswan instead of the VPN setup scripts. Please try my suggestions above.

[1] https://github.com/libreswan/libreswan/issues?utf8=%E2%9C%93&q=is%3Aissue
[2] https://lists.libreswan.org/mailman/listinfo/swan
