### ISSUE TITLE
Just can't reach some site like google.com....

### ISSUE THREAD

**Issue by ChadCSong** [hwdsl2/setup-ipsec-vpn#243]
I found a strange problem.

 Connected successfully via Android by Xauth , but can't open google.com,tumblr.com. 
And I can open Facebook, Twitter directly...  
I have already try google's IP 74.125.204.101 but still can not open it.
Meanwhile my macbook can reach any site by Xauth.
how to solve this problem?

**Comment by hwdsl2** [comment]
@ChadCSong Hello! Can you open those websites on your VPN server (using wget)?

Typically this kind of issues are caused by DNS caching - Try rebooting your Android phone (and VPN server) to clear the cache, then re-connect. In addition, you can also try troubleshooting items 1 and 3 in [1]. Let us know if this solves your issue.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-above

**Comment by wonderxboy** [comment]
Clear cache does not work for me

**Comment by wonderxboy** [comment]
Solved. In my case, it did not work on my mac when I set the VPN type to be L2TP over IPSec. But it works now when I set the type to be Cicso IPSec

**Comment by hwdsl2** [comment]
@wonderxboy Thanks for letting us know.   
@ChadCSong Please see my suggestions in the comment above, or try IPsec/L2TP mode instead.

**Comment by ChadCSong** [comment]
@hwdsl2 IPsec/L2TP is OK now. but I can't use VPN via two platform now( Mac & Android).
