### ISSUE TITLE
connection failed on archlinux

### ISSUE THREAD

**Issue by dotamir** [hwdsl2/setup-ipsec-vpn#249]
Hey, I got failed connection on archlinux!
this is the log when i run ```ipsec up myvpn```
```initiating Main Mode IKE_SA myvpn[1] to 138.197.147.93
generating ID_PROT request 0 [ SA V V V V V ]
sending packet: from 192.168.1.8[500] to 138.197.147.93[500] (212 bytes)
received packet: from 138.197.147.93[500] to 192.168.1.8[500] (144 bytes)
parsed ID_PROT response 0 [ SA V V V ]
received DPD vendor ID
received FRAGMENTATION vendor ID
received NAT-T (RFC 3947) vendor ID
generating ID_PROT request 0 [ KE No NAT-D NAT-D ]
sending packet: from 192.168.1.8[500] to 138.197.147.93[500] (244 bytes)
received packet: from 138.197.147.93[500] to 192.168.1.8[500] (244 bytes)
parsed ID_PROT response 0 [ KE No NAT-D NAT-D ]
no shared key found for 192.168.1.8 - 138.197.147.93
generating INFORMATIONAL_V1 request 3981544278 [ N(INVAL_KE) ]
sending packet: from 192.168.1.8[500] to 138.197.147.93[500] (56 bytes)
establishing connection 'myvpn' failed ```


How i could fix that?

**Comment by hwdsl2** [comment]
@dotamir Hello! I am not familiar with Arch Linux. But this error typically indicate that your VPN client (strongSwan?) cannot read the VPN pre-shared key from `ipsec.secrets` file, which you should double check. Note that on some OS (e.g. CentOS/Fedora), strongSwan requires that `ipsec.conf` and `ipsec.secrets` be placed in `/etc/strongswan` instead of `/etc`.

These example instructions for Linux VPN clients [1] can be used as a reference.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux

**Comment by dotamir** [comment]
Thank you, But I got on Arch Linux we should use ```openswan``` as the client app.
there is a good reference for a config that:
https://wiki.archlinux.org/index.php/Openswan_L2TP/IPsec_VPN_client_setup

thank you again.
