### ISSUE TITLE
Chromebook and Android can't both connect.

### ISSUE THREAD

**Issue by leesah** [hwdsl2/setup-ipsec-vpn#265]
The troubleshooting guide for Chromebook and for Android conflict with each other. Only one device can connect.

### Android
Version 8.0.0
Connects with default setup.
Won't connect when set `phase2alg=aes_gcm-null`

### ChromeOS
Version 63.0.3239.26 (Official Build) beta (64-bit)
Connects only when set `phase2alg=aes_gcm-null`
Won't connect with either the default setup or the `sha2-truncbug=no` workaround.

**Comment by hwdsl2** [comment]
@leesah Hello! Thanks for your report. This is indeed a limitation caused by the different sets of supported VPN ciphers between Android and ChromeOS. There is no good workaround except maybe setting up two VPN servers with different configuration. You can also try specifying different `phase2alg=` in the `conn l2tp-psk` and `conn xauth-psk` sections of `/etc/ipsec.conf`, respectively, and restart the IPsec service. Then let one device connect via IPsec/L2TP, the other connect via Cisco IPsec.
