### ISSUE TITLE
any solutions for ubuntu to connect IPsec/XAuth as a client ?

### ISSUE THREAD

**Issue by xtestw** [hwdsl2/setup-ipsec-vpn#304]
Company provides an IPsec/XAuth vpn for us, but i have a trouble in connectting this vpn in ubuntu 16.04,  is there any solution?

**Comment by hwdsl2** [comment]
@xtestw Hello! On Ubuntu Linux you can try using "vpnc" to connect to the VPN server via IPsec/XAuth. However, because vpnc only supports IPsec "aggressive mode", it is not compatible with the default configuration set up by the VPN scripts, which supports IPsec "main mode" only. You must manually edit /etc/ipsec.conf to make it work. You can find more details at [1] [2] [3].

[1] #152 
[2] #121 
[3] #70

**Comment by trochdewei** [comment]
@xtestw on Fedora I use NetworkManager-libreswan-gnome, but this package is missing in Ubuntu
