### ISSUE TITLE
minor bug

### ISSUE THREAD

**Issue by legale** [hwdsl2/setup-ipsec-vpn#317]
i've just installed ubuntu 17.10 and there is a problem with /etc/rc.local 

rc.local content:

# Added by hwdsl2 VPN script
(sleep 15
service ipsec restart
service xl2tpd restart
[ -f "/usr/sbin/netplan" ] && iptables-restore < /etc/iptables.rules
echo 1 > /proc/sys/net/ipv4/ip_forward)&
exit 0

rc.local runs on boot but 
iptables-restore < /etc/iptables.rules 
does not start.

I've changed [ -f "/usr/sbin/netplan" ] && iptables-restore < /etc/iptables.rules
to  iptables-restore < /etc/iptables.rules

**Comment by hwdsl2** [comment]
@legale Hello! I've been unable to reproduce your issue on a Ubuntu 17.10 system. The IPTables rules were applied successfully upon reboot in my tests.

While not officially supported by the VPN setup script, it does already consider the case of Ubuntu 17.10 where `netplan` is used instead of `ifupdown`. Because the "iptables-restore" script in "/etc/network/if-pre-up.d" is ignored under `netplan`, a line was placed in `/etc/rc.local` to detect the presence of `netplan` and  restore IPTables as necessary.
