### ISSUE TITLE
Dies building Libreswan, Curl issues?

### ISSUE THREAD

**Issue by blacRose** [hwdsl2/setup-ipsec-vpn#32]
a - interfaces.o
		Note: Writing ipsec_version.5
		Note: Writing ipsec_trap_count.5
		Note: Writing ipsec_trap_sendcount.5
		In file included from /usr/include/curl/curl.h:35:0,
		                 from /opt/src/libreswan-3.17/programs/pluto/fetch.c:27:
		/usr/include/curl/curlrules.h:142:3: error: size of array ‘__curl_rule_01__’ is negative
		   __curl_rule_01__
		   ^
		make[3]: *** [fetch.o] Error 1
		make[2]: *** [local-base] Error 2
		make[1]: *** [all] Error 2
		make: *** [all] Error 2

		Libreswan 3.17 failed to build. Aborting.

**Comment by hwdsl2** [comment]
@blacRose This is most likely caused by running a 32-bit (Ubuntu) system but with a 64-bit kernel [1] [2]. 

Check your Linux kernel architecture with:
```
uname -a
```

Then check your system's architecture with [3]:
```
dpkg --print-architecture
```

What are the outputs? If they differ, you need to switch to a kernel that matches your system architecture.

[1] http://ubuntuforums.org/showthread.php?t=1680426
[2] https://bugs.launchpad.net/ubuntu/+source/curl/+bug/723739
[3] http://askubuntu.com/a/447306/491461

**Comment by blacRose** [comment]
Linux hostname 4.5.5-x86_64-linode69 #3 SMP Fri May 20 15:25:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

And

    i386

That is so odd! Like what‽ why‽ how‽ 😕

**Comment by hwdsl2** [comment]
@blacRose Your Linode VPS defaults to use their custom kernel which could lead to this issue. It is recommended that you follow instructions in this article [1] to install a Ubuntu supplied kernel. Please give it a try and let us know whether it solves the issue.

[1] https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distributionsupplied-kernel-with-pvgrub
