### ISSUE TITLE
Can not connect to L2TP through mobile internet.

### ISSUE THREAD

**Issue by badfellowman** [hwdsl2/setup-ipsec-vpn#371]
Russian Federation. I can easily connect through Wi-Fi, but It's impossible with using mobile internet. WHYYYYYY?

**Comment by Twml1500** [comment]
sounds like port forwarding issues, 
you can connect using your router because the server is on same network as the client device. thus no port information needed as the router does LAN stuff automatically. But WAN access you must forward ports. 

Login to your router and forward ports 500 & 4500 to the ip of the server running the vpn.

**Comment by Twml1500** [comment]
Forgot to mention above. Once you port forward you don't use your local 192.168/172.16 address to connect to the VPN. You use your isp public IP. This can be found at whatismyipaddress.com / cmyip.com.

**Comment by hwdsl2** [comment]
@badfellowman Hello! This seems a limitation of your mobile Internet ISP and not an issue of the VPN scripts.
