### ISSUE TITLE
SIOCADDRT: No such device

### ISSUE THREAD

**Issue by kingruseek** [hwdsl2/setup-ipsec-vpn#372]
Hello guys! First of all, thank you hwdsl2 for this excellent VPN working very fast! So into action.
I got an issue while esablishing my VPN client on Kali Linux. I know that Kali ain't 100% Debian but I tried to do it though. So everything was great till the last point:
`root@kali:~# route add default dev ppp0`
`SIOCADDRT: No such device`
Can you please help me to fix it?

**Comment by hwdsl2** [comment]
@kingruseek Hello! This error indicates that device `ppp0` does not exist, which means either the IPsec or L2TP connection was not successfully established. Repeat the steps and check for typos. For further troubleshooting you may check the server logs [1]. Closing because it is not an issue with the VPN scripts.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
