### ISSUE TITLE
Multiple user

### ISSUE THREAD

**Issue by shawondas** [hwdsl2/setup-ipsec-vpn#406]
@hwdsl2 http://prntscr.com/jqwfka would you please check this ?
I don't know how to do the second step for adding multiple users. Multiple users from different router won't be any problem. If so I want to do it.

But i can't figure out to salted and hashed.

we will not use in the same router. Different ISP.

**Comment by shawondas** [comment]
@hwdsl2 Hi sir, will you please check this issue?

**Comment by adahbingee** [comment]
can multiple user use one account to login?
I tried but it seems not available

**Comment by hwdsl2** [comment]
@shawondas Hello! The salting and hashing of VPN passwords can be done using the "openssl" utility. For example, assuming that your additional VPN username is "vpn_username_2", and password is "vpn_password_2", then run:

```
openssl passwd -1 "vpn_password_2"
```

The output will be the salted and hashed password for the additional VPN user. Assume that the output is "ABCDEF". Then edit your /etc/ipsec.d/passwd and add a line like this:

```
vpn_username_2:ABCDEF:xauth-psk
```

Repeat these steps for more VPN users.

@adahbingee Please see important notes [1]. The same VPN account can be used by your multiple devices. However, due to an IPsec/L2TP limitation, if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use only IPsec/XAuth mode [2]. Also, double check that your Libreswan version is 3.22 using `ipsec --version`. If not, re-run the VPN setup script.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
