### ISSUE TITLE
Multiples ips in server and NAT connection for clients

### ISSUE THREAD

**Issue by desis123** [hwdsl2/setup-ipsec-vpn#408]
I have centos cpanel server with five ip address. and my clients are behind a NAT connection (Home Router) with windows PC . I like to configure VPN server to connect all server ip individually . So my clients who are behind one router they will get dedicated ip for each device. How I can do that  ... any advice will be appreciated. I am pretty new in this field. So your advice will help me a lot.

**Comment by hwdsl2** [comment]
@desis123 Hello! For your use case, you can specify each of the five IPs as the VPN server IP in each of your VPN clients. This way they can connect simultaneously to the VPN server. However, I am not sure how your VPN clients can each get a different "outgoing IP". They would normally get the same outgoing IP due to the VPN server only having one default route.
