### ISSUE TITLE
Updated to debian stretch and now failing to connect

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#419]
Updated Debian jessie to stretch and now I cannot ipsec connect and I see the following in `/var/log/auth.log`:

```
Jul 15 00:04:49 pi pluto[2461]: packet from 174.196.130.72:9492: initial Main Mode message received on 192.168.0.3:500 but no connection has been authorized with policy PSK+XAUTH+IKEV1_ALLOW
```

**Comment by hwdsl2** [comment]
@nodesocket Hello! Check if your logs contain lines like this:
```
May  5 21:57:33 myhost pluto[XXX]: connection l2tp-psk must specify host IP address for our side
May  5 21:57:33 myhost pluto[XXX]: Failed to load connection "l2tp-psk": attempt to load incomplete connection
May  5 21:57:33 myhost pluto[XXX]: connection xauth-psk must specify host IP address for our side
May  5 21:57:33 myhost pluto[XXX]: Failed to load connection "xauth-psk": attempt to load incomplete connection
```

If so, make the following changes in `/etc/ipsec.conf`. Find the line `left=%defaultroute` and replace it with `left=YOUR_PRIVATE_IP`, indented with two spaces, where `YOUR_PRIVATE_IP` is the local (private) IP of your Raspberry Pi server, e.g. `192.168.0.3`. Save the file and run `service ipsec restart`. Now retry the VPN connection.

It is recommended to make a DHCP reservation for the Raspberry Pi so that its private IP does not change. Otherwise you'll need to update that file again.

More information about this issue can be found in [1] [2].

[1] https://github.com/libreswan/libreswan/issues/177
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L290-L293

**Comment by nodesocket** [comment]
Yup changing  `left=%defaultroute` to `left=192.168.0.3` and restarting the ipsec service worked. Strange was that a breaking change from jessie to stretch can't use `%defaultroute`?

**Comment by hwdsl2** [comment]
@nodesocket It only occurs in some systems such as Raspberry Pi w/ Debian Stretch and Ubuntu 18.04 on Amazon EC2, where `ip route list` shows `src ...` in the default route line. See [1] for more information. The Libreswan team has not yet responded further on this issue. You may use the workaround above for now.

[1] https://github.com/libreswan/libreswan/issues/177#issuecomment-390090178
