### ISSUE TITLE
VPN能连接，但访问不了外网

### ISSUE THREAD

**Issue by jahentao** [hwdsl2/setup-ipsec-vpn#473]
您好，我使用您的脚本成功搭建了VPN，VPN服务器是Google Cloud Platform，客户端是Windows10内置，能够连接。
客户端可以访问百度，但无法访问Google，本地的DNS我也修改过了，仍然无法访问外网。
查看iptables，如下

```
# iptables -t nat -nvL

Chain PREROUTING (policy ACCEPT 98 packets, 10980 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 5 packets, 1104 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 8 packets, 480 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 8 packets, 480 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      ens4    192.168.42.0/24      0.0.0.0/0           
    0     0 MASQUERADE  all  --  *      ens4    192.168.43.0/24      0.0.0.0/0            policy match dir out pol none
```

我感觉离曙光很近了，但不知道怎么改

**Comment by jahentao** [comment]
更新了一下Windows10本地的DNS缓存`ipconfig /flushdns`，但是没有用

**Comment by hwdsl2** [comment]
@jahentao 你好！Windows 10 在某些情况下会在所有网卡上同时进行 DNS 解析。对于 IPsec VPN，尝试以下解决方案：

1. 将你主要网卡上的 DNS 服务器换成比如 8.8.8.8 和 8.8.4.4（只要不在你的本地网段就可以），或者
2. 关掉 smart multi-homed name resolution [1].

在完成后，重启你的电脑，flush dns，然后应该就可以了。

[1] https://www.neowin.net/news/guide-prevent-dns-leakage-while-using-a-vpn-on-windows-10-and-windows-8/

**Comment by jahentao** [comment]
@hwdsl2 您好，还是不行。我原先的`multi-homed name resolution`是关闭的，DNS已经在主要网卡上配置了。仍然是可以连接，但 cmd 无法ping通google。

**Comment by hwdsl2** [comment]
@jahentao 你好！再试一下清除 DNS 缓存：打开提升权限命令提示符，运行 `ipconfig /flushdns`。

如果还不行，另外试一下 IPsec/XAuth 模式（使用 Shrew Soft VPN Client）或者 IKEv2。详见 README。

**Comment by jahentao** [comment]
@hwdsl2 根据README中配置Shrew Soft VPN Client，在连接的时候，会出现一个`negotiation timout occurred`的错误。

**Comment by flymorn** [comment]
@jahentao 

Error : "negotiation timout occurred"

This problem is caused by a conflict between the VPN software and the Microsoft Virtual WiFi Miniport adapter. This problem only occurs on Windows 7.

In case anyone wonders where they can find out if they have a "Microsoft Virtual WiFi Miniport Adapter" installed, go to network and sharing center, then click "change adapter settings". there should be a **Microsoft Virtual Wifi Miniport Adapter** if you have it. 

when disabled **Microsoft Virtual Wifi Miniport Adapter**, my vpn connection succeeded as well.
