### ISSUE TITLE
PowerShell for configuring Windows VPN

### ISSUE THREAD

**Issue by nzbart** [hwdsl2/setup-ipsec-vpn#478]
The instructions on configuring connections from Windows could be simplified or automated by using the following PowerShell commands:

```powershell
Add-VpnConnection -Name "IPSec VPN" -ServerAddress <VPN IP address> -TunnelType L2tp -RememberCredential -L2tpPsk <pre-shared key> -AuthenticationMethod MSChapv2 -EncryptionLevel Maximum -Force
Set-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\PolicyAgent AssumeUDPEncapsulationContextOnSendRule -Type DWord -Value 2 -Force
Restart-Computer
```

Note that I have used MSChapv2 because it supports encryption, whereas Chap as recommended in the documentation does not. Is there any reason that Chap is required in the documentation?

**Comment by hwdsl2** [comment]
@nzbart Hello! Thank you for suggesting the Powershell command, will add it to the docs. 

Regarding CHAP vs. MSCHAPv2, previously only CHAP is supported in the script, but since we added the `+mschap-v2` option to /etc/ppp/options.xl2tpd, both CHAP and MSCHAPv2 can now be used. Either one works fine. The authentication is encrypted because it happens within the IPsec VPN tunnel.

**Comment by letoams** [comment]
You do not need encryption at the L2TP layer because you encrypt at the IPsec layer
