### ISSUE TITLE
VPN client for Xauth + PSK on Windows

### ISSUE THREAD

**Issue by lncan** [hwdsl2/setup-ipsec-vpn#504]
Hi guys, I follow the instruction via link https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md to connect vpn server on window. But no successful. Here is error picture.

![48277810_2099262406784157_21906476398280704_n](https://user-images.githubusercontent.com/40355589/49730453-fc293900-fcaa-11e8-90f9-4371691924ba.png)

Can you please tell me the detail solution to fix this or any solution to connect vpn on window? Thanks all.

**Comment by hwdsl2** [comment]
@Incan Hello! Because you are trying to connect to a Fortigate VPN server [1][2], not a VPN server set up using scripts in this repo, I would suggest that you instead ask in the relevant community or the Libreswan mailing list [3].

[1] libreswan/libreswan#227
[2] libreswan/libreswan#228
[3] https://lists.libreswan.org/mailman/listinfo/swan
