### ISSUE TITLE
How to add multiple leftsubnets?

### ISSUE THREAD

**Issue by rysi3k** [hwdsl2/setup-ipsec-vpn#530]
Hello
I have configured XAuth-PSK and it works, with addresses 10.9.0.2-10.9.0.200 (as `rightaddresspoll`)
On IPSec server I have another networks (10.88.0.0/16 and 10.99.0.0/24), to which I want to access throuh vpn.
I wanted not to redirect default gateway, so I have `leftsubnet=10.88.0.0/16` + NAT and it works.
But when i want to add second network `leftsubnets={10.88.0.0/16,10.99.0.0/24}` i can't connect to VPN anymore.
In logs i have `Main Mode message received on SERVER_IP:500 but no connection has been authorized with policy PSK+XAUTH+IKEV1_ALLOW`.
How can I achive it?

Thanks in advance

**Comment by hwdsl2** [comment]
@rysi3k Hello! That error message typically means your connection was not added due to a config error when Libreswan starts. Check the Libreswan logs [1] to see what config error it was. 

I am not familiar with the `leftsubnets` syntax, but here are some examples [2]. You will also need to update your IPTables rules in the FORWARD and/or NAT chain in order to allow traffic to/from your desired subnets. For further questions, please reach out to the experts on the Libreswan users mailing list [3].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
[2] https://github.com/libreswan/libreswan/search?utf8=✓&q=leftsubnets&type=
[3] https://lists.libreswan.org/mailman/listinfo/swan

**Comment by letoams** [comment]
On Wed, 20 Feb 2019, rysi3k wrote:

> I have configured XAuth-PSK and it works, with addresses 10.9.0.2-10.9.0.200 (as rightaddresspoll)
> On IPSec server I have another networks (10.88.0.0/16 and 10.99.0.0/24), to which I want to access throuh vpn.
> I wanted not to redirect default gateway, so I have leftsubnet=10.88.0.0/16 + NAT and it works.
> But when i want to add second network leftsubnets={10.88.0.0/16,10.99.0.0/24} i can't connect to VPN anymore.
> In logs i have Main Mode message received on SERVER_IP:500 but no connection has been authorized with policy PSK+XAUTH+IKEV1_ALLOW.
> How can I achive it?

Support for multiple subnets works with libreswan as a client, but has
not been implemented for libreswan as a server.

It is likely not a huge effort to code, but it hasn't been a high
priority of the libreswan developers.

Paul

**Comment by rysi3k** [comment]
Thanks @letoams
Have you domek idea how to workaround it?

**Comment by letoams** [comment]
No workaround other than using one subnet or 0.0.0.0/0.
