### ISSUE TITLE
There was a problem with the second connection

### ISSUE THREAD

**Issue by Coding-01** [hwdsl2/setup-ipsec-vpn#550]
Hello, I am honored to see this vpn project. I used this project at work and successfully built and used it for the first time. (One client A <centos7.4.1708> in the LAN is connected to the host on the Internet)

Because the host on the Internet changed, so you need to re-establish the connection, this time a problem .....

Always prompted when executing strongswan up myvpn:
Sending retransmit 2 of request message ID 0, seq 1
Sending packet: from 192.168.1.129[500] to 114.xxx.xx.44[500] (180 bytes)
Sending retransmit 3 of request message ID 0, seq 1
Sending packet: from 192.168.1.129[500] to 114.xxx.xx.44[500] (180 bytes)
Sending retransmit 4 of request message ID 0, seq 1
Sending packet: from 192.168.1.129[500] to 114.xxx.xx.44[500] (180 bytes)
Sending retransmit 5 of request message ID 0, seq 1

I saw it in /var/log/messages :
07[IKE] establishing IKE_SA failed, peer not responding

After checking for a long time, I didn’t get the result. I finally thought of giving you feedback.
Thank you! !
(Maybe my English is not very good)

I can establish a connection on other CentOS7.4.1708 or windows. A machine has docker installed on it.

**Comment by Coding-01** [comment]
I can connect normally on other CentOS7.4.1708 or windows, and docker can be installed on this machine.

**Comment by hwdsl2** [comment]
@Coding-01 Hello! You mentioned that you can successfully establish a VPN connection on other CentOS or Windows. So it is not an issue with the VPN server itself. This is most likely caused by network issues of the CentOS machine in question (it could not reach the VPN server). Also, make sure that you put the correct VPN server IP in the client's VPN configuration.
