### ISSUE TITLE
Access l2tp/ipsec client from l2tp server network. Is it possible?

### ISSUE THREAD

**Issue by lawin1** [hwdsl2/setup-ipsec-vpn#555]
Hello! 

I have installed your IPsec VPN Server auto setup script on Raspbery Pi. All configuration is default. There is only one lt2p/ipsec client - Mikrotik router. Everything works very well!

Network diagram:

 Mikrotik router behind LTE mobile network NAT (Internal IP 192.168.88.1, l2tp/ipsec client IP 192.168.42.10)
I
I
 Internet
I
I
 Asus router (with ports forwarding 500, 1701, 4500 - Internal IP 192.168.11.1)
I
I
Raspberry Pi as VPN server (Internal IP - 192.168.11.76, L2TP server IP 192.168.42.1)

If VPN connection is active, Raspberry Pi and Mikrotik router can ping each other. Any other PC which are connected to Asus router cannot ping neither L2TP server (192.168.42.1) nor Mikrotik router (192.168.42.10). If I manually set gateway 192.168.11.76 in network preferences of PC "A" then this PC can ping 192.168.42.1 (l2tp server), but still cannot ping 192.168.42.10. Is it standard behaviour? What can I do in order to access lt2p/ipsec client from PC "A"?

**Comment by hwdsl2** [comment]
@lawin1 Hello! I understand that you want to allow access from devices on the VPN server's network to the VPN client. Similar issues was discussed before [1][2].

For your use case: First, devices on the Asus router network should use the VPN server's local IP (192.168.11.76) instead of its internal VPN IP (192.168.42.1) to access the VPN server itself.

Second, the reason that you cannot ping 192.168.42.10 after setting gateway 192.168.11.76 is because access to VPN clients is disallowed for security reasons in the default IPTables FORWARD rules set up by the script. In other words, connections initiated from the Internet (or VPN server's network) to the VPN client are dropped. However, you may modify IPTables rules to allow access from/to your subnet:

```
# For IPsec/L2TP
iptables -I FORWARD 2 -i ppp+ -d 192.168.11.0/24 -j ACCEPT
iptables -I FORWARD 2 -s 192.168.11.0/24 -o ppp+ -j ACCEPT

# For IPsec/XAuth ("Cisco IPsec")
iptables -I FORWARD 2 -s 192.168.43.0/24 -d 192.168.11.0/24 -j ACCEPT
iptables -I FORWARD 2 -s 192.168.11.0/24 -d 192.168.43.0/24 -j ACCEPT
```

You'll still need to set the gateway (or add a route) for PC "A". To make these IPTables rules persist after reboot, you may add them to file /etc/iptables.rules and/or /etc/iptables/rules.v4 (Ubuntu/Debian), or /etc/sysconfig/iptables (CentOS/RHEL).

Let us know if this works.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/141
[2] https://github.com/hwdsl2/setup-ipsec-vpn/issues/554

**Comment by lawin1** [comment]
Thank you for your efforts to help me with a comprehensive answer! In this case I do not care about security. I added rules to a file /etc/iptables.rules and rebooted raspberry Pi. Unfortunately, IPTables rules you have provided does not help to reach 192.168.42.10 from PC "A" ( as required, its gateway set manually to 192.168.11.76), but have unexpected positive effect. Before your rules, PC "A" with gateway 192.168.11.76 did not have access to Internet. After rules applied PC "A" can access Internet. But it is not an effect I was looking for :)

Maybe I have to disable any DROP rules in a file /etc/iptables.rules? I tried to disable all of them (commented out with #), bet after that l2tp client cannot access Internet although it is still connected to the l2tp server.

**Comment by lawin1** [comment]
https://ibb.co/qYXM64G

Windows PC2 is PC "A" in this case.

**Comment by hwdsl2** [comment]
@lawin1 Thank you for the details. You can try to comment out just the last "DROP" rule in the IPTables "FORWARD" chain to see if it helps (and restore it after). Other DROP rules may not be related.

Since you can reach 192.168.42.10 from the VPN server, it looks like we'll need to let the VPN server route traffic from PC "A" to 192.168.42.10. That may not be easy though. Because 192.168.42.10 is an internal VPN IP, perhaps you can instead try to access 192.168.88.1 by adding the relevant IPTables FORWARD rules and routing?

What might work better for your use case are "site-to-site" VPNs. For example, you can build a site-to-site VPN that connects your subnet 192.168.88.0/24 to your subnet 192.168.11.0/24, and let devices communicate across the subnets. You can find more examples at [1]. However, this is outside the scope of this project, which sets up a "road warrior" VPN.

I suggest that you ask further questions on the Libreswan or strongSwan users mailing lists, where many VPN experts could help with your use case.

[1] https://libreswan.org/wiki/Configuration_examples
