### ISSUE TITLE
Site-to-site VPN connection

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#556]
Can I use this to setup a site-to-site VPN connection with a network router?

**Comment by hwdsl2** [comment]
@nodesocket If you use a network router that supports connecting to IPsec/L2TP or Cisco IPsec VPNs, you may use it to directly connect to the VPN server, so that all devices behind the router will use the VPN automatically. No site-to-site VPN configuration is needed. Let’s continue the discussion in #557.
