### ISSUE TITLE
Can't connect to youtube via xauth connection

### ISSUE THREAD

**Issue by MasihIT** [hwdsl2/setup-ipsec-vpn#560]
Hello. I have a strange problem. When I connect to my server via l2tp, There is no problem to access to google servers. (.eg youtube except google.com only)
But when I connect via Xauth, google servers won't open. (except google.com)
I have tried to change sha2-trunsbug, restart my server and my android phone but None of them worked for me.

What should I do now?

**Comment by hwdsl2** [comment]
@MasihIT Hello! Can you test to see if you are unable to open any website via IPsec/XAuth? If so, it could indicate a VPN cipher issue.

**Comment by MasihIT** [comment]
Yes, I can open all website I want. Only Google servers except google.com don't response. I should also add that I can ping google servers on my vpn server.
What's the VPN cipher issue?

**Comment by hwdsl2** [comment]
@MasihIT In that case it cannot be a VPN cipher issue (otherwise you'll be unable to open any website). If the issue occurs only on Android but not on your other devices, I think it could be due to some bug on Android for IPsec/XAuth VPNs, and not a problem with the VPN server itself.

Unfortunately I had never encountered this particular issue before. Try searching for similar issues in my repos and the web, troubleshoot further yourself using network tools, and/or reach out to the relevant communities such as those for your Android device and the Libreswan or strongSwan users mailing list.
