### ISSUE TITLE
The L2TP-VPN server did not respond

### ISSUE THREAD

**Issue by xl2tpd** [hwdsl2/setup-ipsec-vpn#582]
I installed a clean copy of CentOS 7 on a Parallels virtual machine (before messing with the VPN setup on a production environment). The network is the default shared network and I have not problem connecting to other services such as ssh, etc.

Then ran the vpnsetup_centos.sh script, it finished with a bizarre server ip in the last bit of the output. The only thing I can tell is from whois database it's an ip address from the same ISP I'm connected but it's not *my* external ip whatsoever.

I checked "service xl2tpd status" and "netstat -nl" to confirm it's listening on udp 0.0.0.0:1701 anyway.

I also had "tcpdump 'udp port 1701'" to see if anything actually happens.

Then I tried connecting from my VM host machine which is a Mac.

After a few seconds "connecting...." it gave up with the following message:
The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.

The problem is I can't even find any error log whatsoever from the CentOS machine; not even tcpdump captured a single packet.

So I suppose my question is where is my starting point to debugging? As with the current nonexistence of information I seriously struggle on how to proceed with this business...

**Comment by kylepwarren** [comment]
Side question: Can I use multiple *different* users one the *same* lan with IPsec/L2TP. The documentation is not clear, it looks like it may means you just can't use the same credentials on the same LAN (more than once)?

**Comment by letoams** [comment]
On Tue, 25 Jun 2019, Kyle Warren wrote:

> Side question: Can I use multiple different users one the same lan with IPsec/L2TP. The documentation is not clear, it looks like it may means you just can't use the same credentials on the same LAN (more
> than once)?

It should work. re-using the same username/passwd should kick of the
older instance (but not sure if it actually does)

Paul

**Comment by hwdsl2** [comment]
@xl2tpd Hello! Your use case is special because you are setting up the VPN server on a virtual machine and try to connect to it from the host, instead of connecting from outside your network. The fact that you didn't see logs is probably because traffic did not reach your VPN server.

For your use case, ignore the public IP printed at the end of VPN setup (which does not apply in your setup), but instead configure your VPN client to connect (from the host) using the Parallels virtual machine's internal IP on the shared network you mentioned.
