### ISSUE TITLE
Successfully connected in XAuth mode but cannot access the network.

### ISSUE THREAD

**Issue by chaocaiwei** [hwdsl2/setup-ipsec-vpn#584]
Hi.

My current situation is this:
1, I can connect to the VPN and access the network with my iPhone
2, using my mac to connect in L2TP mode is also working properly
3. When I connect to the VPN in Cisco IPSec mode, I can't connect to the network, and ping any address is timeout.
4. My server system is Ubuntu 18.04.1 LTS
5. My Mac is the latest beta 10.15 beta Catalina

**Comment by kylepwarren** [comment]
Same here. debian 9 server, android client. L2TP works, If I change to XAUTH it says connected, but not internet

**Comment by kylepwarren** [comment]
side question: Can different user credentials use IPsec/L2TP on the same lan? the documentation is not clear if it's really limited to devices or credential.

**Comment by shaomeng** [comment]
I experience the same issue with the following platforms:
- Server: docker image running on a raspberrypi
- Client: Pixel 2 (Android 9) on TMobile LET network

**Comment by hwdsl2** [comment]
@chaocaiwei To help troubleshoot, can you post your latest logs (see [1]) when connecting with Cisco IPsec mode, with IPs redacted?

@kylepwarren @shaomeng For your Android client issue, it is probably caused by the `sha2-truncbug` setting. try step 2 in [1].

@kylepwarren The IPsec/L2TP limitation is for devices, not credentials, so technically you cannot work around it by using different user credentials on devices from behind the same NAT.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-above

**Comment by hwdsl2** [comment]
@chaocaiwei If the problem persists please open a new issue with the requested details.
