### ISSUE TITLE
VPN Client question

### ISSUE THREAD

**Issue by kylepwarren** [hwdsl2/setup-ipsec-vpn#589]
This is a pretty general VPN client questions, I looked all over the internet and couldn't find a good place to ask it, so since this is the server I use, I'll ask it here.

I use android VPN, and like using the "Always on" setting, otherwise it seems the VPN connection could drop at anytime with little to no warning. 

For some reason, the always on setting requires I fill in both an IP for DNS, *and* server name, though the text only mentions needing an IP for DNS... 

Also, the bigger issue I'm having: when at the same location as the VPN server(same LAN), the always on settings (actual IP addresses) seem to cause some sort of problem, and I get no connectivity. If I have just domain name(not always on), connectivity still works when VPN connected on same LAN.

I guess I'll leave this kind of vague, but **my goal is essentially: always on VPN, that will still work when I am on the same LAN as the VPN server.** If I need another client[on android], that's fine. Or it may be a server setting. Not sure.

**Comment by letoams** [comment]
On Thu, 27 Jun 2019, Kyle Warren wrote:

> I use android VPN, and like using the "Always on" setting, otherwise it seems the VPN connection could drop at
> anytime with little to no warning.
> 
> For some reason, the always on setting requires I fill in both an IP for DNS, and server name, though the text
> only mentions needing an IP for DNS...

I don't know about this...

> Also, the bigger issue I'm having: when at the same location as the VPN server(same LAN), the always on
> settings (actual IP addresses) seem to cause some sort of problem, and I get no connectivity. If I have just
> domain name(not always on), connectivity still works when VPN connected on same LAN.
> 
> I guess I'll leave this kind of vague, but my goal is essentially: always on VPN, that will still work when I
> am on the same LAN as the VPN server. If I need another client[on android], that's fine. Or it may be a server
> setting. Not sure.

This usually happens if you assign IP addresses to the VPN clients from
the local LAN, or when you are blocking from accessing the external IP
of the VPN server from the inside LAN. In the first case, your client
would have an IP within a subnet (say 10.0.0.X/24) and getting a lease
IP of 10.0.0.Y results in your traffic being sent out before the routing
table moves the packet into the IPsec subsystem (as there is no routing
needed for LAN packets). I don't know how or if Android handles this.

In the second case, it could be eg rp_filter or firewall rules
wrongly kicking in could cause this, since you are connecting to the
"remote" side of the VPN server, and then after IPsec decryption, your
packets with source IP of the LAN appear to have been received from
the "wrong" interface and rp_filter prevents this. Check to see if
rp_filter et all is disabled or not.

You could configure two IPsec conncetions on the server, one with a
left= of the internal IP and one with the left of the external IP,
then have DNS hand out the proper IP. If also using an addresspool
that is seperate from the LAN, I think that should always result
in working connections?

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams!

@kylepwarren In the default configuration set up by the VPN scripts, the `left=` in your `/etc/ipsec.conf` should already be set to your VPN server's internal IP. Therefore, while you are on the same LAN as the VPN server, change your always-on VPN to use the VPN server's internal IP to connect (e.g. 192.168.1.1). And change it back to the external IP when you move off the LAN.
