### ISSUE TITLE
ip6tables error

### ISSUE THREAD

**Issue by ikelca** [hwdsl2/setup-ipsec-vpn#6]
ip6tables-restore v1.4.7: ip6tables-restore: unable to initialize table 'filter'

Error occurred at line: 2
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.

**Comment by ikelca** [comment]
environments: centOS 6 X64 
commented out
#PUBLIC_IP=$(wget --retry-connrefused -t 3 -T 15 -qO- 'http://169.254.169.254/l$
#PRIVATE_IP=$(wget --retry-connrefused -t 3 -T 15 -qO- 'http://169.254.169.254/$

**Comment by hwdsl2** [comment]
@ikelca I think this error can be safely ignored in your case. Is the VPN working fine?

**Comment by ikelca** [comment]
VPN seems working fine as i tested, what could be the cause of this error?

**Comment by hwdsl2** [comment]
This error is because IPv6 or its kernel module is disabled on your server. As a result, IP6Tables is unable to load the new IPv6 rules. For the VPN this should not matter because only IPv4 is used. You can safely ignore this unless you wish to use IPv6. Refer to [1] and [2] below.

[1] http://pks-sme.blogspot.kr/2012/03/applying-ip6tables-firewall-rules.html?m=1
[2] https://bugzilla.redhat.com/show_bug.cgi?id=642268

**Comment by ikelca** [comment]
thanks for the fast reply, you are the best!

**Comment by hwdsl2** [comment]
Fixed in 01b5cf1.
