### ISSUE TITLE
Internet does not work on iOS 13

### ISSUE THREAD

**Issue by zhuravel-sergey** [hwdsl2/setup-ipsec-vpn#605]
Hello!
In iOS 13 Apple banned the use of old TLS certificates, and because of this, the VPN is connected but the Internet does not work.

some new guidelines for iOS 13: https://support.apple.com/en-us/HT210176
discussion on the forum Apple: https://forums.developer.apple.com/thread/118316

Guys, please update the script configuration to the new Apple requirements.
Thx!

**Comment by hwdsl2** [comment]
@zhuravel-sergey Hello! Thanks for reporting. For this particular issue, if your iOS 13 device can successfully connect using IPsec/XAuth or IPsec/L2TP mode, but the Internet does not work, it is because of the `sha2-truncbug` setting. Try the following fix:

Edit `/etc/ipsec.conf` and replace `sha2-truncbug=yes` with `sha2-truncbug=no`, save the file and run `sudo service ipsec restart`. Now try to re-connect.

Regarding the new TLS certificate requirements for IKEv2 in iOS 13, I'll look into that separately when I get a chance.

**Comment by SSmale** [comment]
I have replaced the sha2-truncbug but am still unable to reach the internet on my iOS 12.4 using the IPsec connection type. 

Anything else that can cause the issue?

**Comment by solidusex** [comment]
解决了，十分十分感谢，谢谢.
