### ISSUE TITLE
No mobile connection to VPN Server

### ISSUE THREAD

**Issue by BopaxDev** [hwdsl2/setup-ipsec-vpn#611]
I have installed your script on my raspberry pi.
I have opened my port on router and I set up my dmz settings, but i don't know why it doesn't work. I also installed an http server with apache but it works if I insert my public ip on a web browser it works but not for vpn.

**Comment by hwdsl2** [comment]
@BopaxDev Hello! To troubleshoot, Libreswan and xl2tpd logs can be checked using these commands [1]. See if the logs contain any error, and post the error here. On the other hand, if there is no new log after trying to connect, then traffic did not reach your VPN server and you'll need to check your firewall and port forwarding settings.

If not already forwarded, please forward UDP port 500 and UDP port 4500 on your router to your Raspberry Pi's local IP. It is recommended to reserve a static local IP for your RPi on the router, so it does not change on reboot (otherwise you'll need to forward the ports again).

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by BopaxDev** [comment]
I'll try it

**Comment by BopaxDev** [comment]
I have solved the problem, Pi was giving me some errors so i have decided to install your vpn server on ubuntu server.

Thanks for all.
