### ISSUE TITLE
LCP: timeout sending Config-Requests

### ISSUE THREAD

**Issue by ptorrent** [hwdsl2/setup-ipsec-vpn#642]
Hello there !

Sometimes from windows, it is impossible for me to connect to the server (PPTP):

```
pppd[4789]: Plugin /usr/lib/pptpd/pptpd-logwtmp.so loaded.
pppd[4789]: pppd 2.4.7 started by root, uid 0
pppd[4789]: Using interface ppp0
pppd[4789]: Connect: ppp0 <--> /dev/pts/0
pppd[4789]: LCP: timeout sending Config-Requests
pppd[4789]: Connection terminated.
pppd[4789]: Modem hangup
pppd[4789]: Exit.
```

Do you think it is a problem with Windows or with the server? I need to restart windows for it to work.

When the problem appears, I can connect from another Windows or Android machine. 

Is there a solution to consider on the server to prevent this kind of problem?

Thank you for your feedback!

**Comment by hwdsl2** [comment]
@ptorrent Hello! I think you were referring to IPsec/L2TP because this project is for IPsec VPN server, not PPTP.

From your logs, it is most likely a network issue between your VPN client and the VPN server. You can further check the Libreswan and/or L2TP logs [1] to see if there is any error. Note that connecting multiple IPsec/L2TP VPN clients from behind the same NAT (e.g. home router) is not supported, as mentioned in the important notes section of the README.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
