### ISSUE TITLE
Deployment to Azure fails when special characters used for PSK

### ISSUE THREAD

**Issue by turbozapekanka** [hwdsl2/setup-ipsec-vpn#644]
Error message from the deployment log:
...
 "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'installcustomscript'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=2\n[stdout]\n\n[stderr]\n/bin/sh: 1: Syntax error: \"(\" unexpected\n\"." } ] } }, 
...

**Comment by turbozapekanka** [comment]
the reason is no escaping done for passwords with special characters

**Comment by turbozapekanka** [comment]
For example using this PSK will cause the deployment to fail: (d_Tfiz,(K{2CzrL|5k_`<RV

**Comment by letoams** [comment]
On Mon, 7 Oct 2019, turbozapekanka wrote:

> For example using this PSK will cause the deployment to fail: (d_Tfiz,(K{2CzrL|5k_`<RV

I just ran a PSK interop test between strongswan and libreswan with this
exact PSK, and it worked. So that would suggest the problem is more likely
to appear on the Azure side. I would try removing the "`" character,
as that is a shell escape character and it might be filtered out for
security reasons.

Paul

**Comment by turbozapekanka** [comment]
I'm pretty sure this is azure deployment template issue, see azuredeploy.json:

        "installScriptURL": "https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/azure/install.sh",
        "installCommand": "[concat('sh install.sh ', parameters('preSharedKey'), ' ', parameters('username'), ' ', parameters('password'))]"
