### ISSUE TITLE
macOS Catalina connects but no traffic routing through tunnel -- sha2-truncbug

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#652]
Today upgraded  to macOS Catalina and none of my Cisco IPSec connections are routing traffic even though they successfully connect. The following post on Apple suggested updating the server `/etc/ipsec.conf` from ` sha2-truncbug=yes` to `sha2-truncbug=no`.

https://forums.developer.apple.com/thread/121193

Can you confirm this?

**Comment by hwdsl2** [comment]
@nodesocket Hello! Thanks for reporting. Although I have not tested this myself, user feedback suggests that what you observed is true. This was fixed in commit 3353888 and the troubleshooting section [1] had been updated.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ios-13-and-macos-1015
