### ISSUE TITLE
Can't connect to the other networks if VPN server has multiple networks

### ISSUE THREAD

**Issue by sachinpk** [hwdsl2/setup-ipsec-vpn#674]
I tried to Setup an L2TP VPN on my DigitalOcean server with a private network and successfully connected to the VPN. But I'm not able to connect to the private IP address of other servers on the same network where I did the VPN setup. Do I need to make any modification to the configuration if had multiple networks on the server?

**Comment by letoams** [comment]
If you hand out same private ip range you need proxy arp enabled on the interface.
If you hand out different ip, it needs to be routable to the other machines or be NAT’ed to the servers private ip

**Comment by hwdsl2** [comment]
@sachinpk Hello! Please try the instructions in [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#access-vpn-servers-subnet

**Comment by kakarukeys** [comment]
hi the above link does not work. could you post an updated link? I wish to read the instructions.

**Comment by hwdsl2** [comment]
@kakarukeys Please see: https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/174#issuecomment-827323565

**Comment by kakarukeys** [comment]
@hwdsl2 I tried the default settings, then default settings + the extra ip-route rules. They did not work.

I guess it's because the private network is on another interface. I created my server on DigitalOcean, a commonly used cloud provider for private VPN servers.

On my server, the public internet interface is on eth0, and the private network interface (10.122.0.1/20) is on eth1. How should I change the routing rules?

I'd like to connect to any service on private network, e.g. `curl http://10.122.0.3` from my laptop (VPN client).

**Comment by hwdsl2** [comment]
@kakarukeys I've tested this use case. You'll need to add IPTables rules by running these commands:
```
  iptables -I FORWARD 2 -i eth1 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  iptables -I FORWARD 2 -i ppp+ -o eth1 -j ACCEPT
  iptables -I FORWARD 2 -i eth1 -d 192.168.43.0/24 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  iptables -I FORWARD 2 -s 192.168.43.0/24 -o eth1 -j ACCEPT
  iptables -t nat -I POSTROUTING -s 192.168.43.0/24 -o eth1 -m policy --dir out --pol none -j MASQUERADE
  iptables -t nat -I POSTROUTING -s 192.168.42.0/24 -o eth1 -j MASQUERADE
```

To make these IPTables rules persist after reboot, you may add them to file `/etc/iptables.rules` and/or `/etc/iptables/rules.v4` (Ubuntu/Debian), or `/etc/sysconfig/iptables` (CentOS/RHEL).

**Comment by kakarukeys** [comment]
Thank you. It works perfectly.
