### ISSUE TITLE
IKEv2 error Windows 10

### ISSUE THREAD

**Issue by anartikov** [hwdsl2/setup-ipsec-vpn#723]
Sorry for my english.
I use a translator.
Configured everything as you indicated.
I'm trying to connect - error.
"Cannot connect to vpn. Group Policy mapping error"
I am ready to provide you with any information. Help solve this problem.

**Comment by anartikov** [comment]
Jan 31 22:06:45 NartServ2 pluto[1804]: packet from 109.252.113.91:2434: initial parent SA message received on 116.203.181.10:500 but no suitable connection found with IKEv2 policy
Jan 31 22:06:45 NartServ2 pluto[1804]: packet from 109.252.113.91:2434: responding to IKE_SA_INIT (34) message (Message ID 0) from 109.252.113.91:2434 with unencrypted notification NO_PROPOSAL_CHOSEN

**Comment by hwdsl2** [comment]
@anartikov Hello! Please make sure that you restarted the IPsec service (`sudo service ipsec restart`) after following the steps from the IKEv2 docs [1]. Otherwise, the IKEv2 section in `/etc/ipsec.conf` will not take effect.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md

**Comment by anartikov** [comment]
I did it. The error is repeated.
