### ISSUE TITLE
VPN Server apparently not reachable

### ISSUE THREAD

**Issue by PierfrancescoElia** [hwdsl2/setup-ipsec-vpn#727]
Hi, 
I've been using this software for a month, but I sometimes run into a problem.
I've a Mikrotik RouterBoard (from now on RB) that _should_ be always connected to the VPN.

Sometimes the RB disconnects form VPN, and it stays in a _connecting_ status.
To restore the connection I need to restart the VPS or restart IPSec and xl2tpd services (read from [here](https://github.com/hwdsl2/setup-ipsec-vpn/issues/104#issuecomment-275170425)).

I'm not able to figure out how or why this is happening, because I can't find log files.

Goal is to have a VPN Server running 24/7 without any issues, because is a VoIP PBX that can't stay disconnected.

Thank you in advance for your help.

--
VPS from AWS with CentOS 7
Linux Libreswan 3.29 (netkey) on 3.10.0-1062.4.1.el7.x86_64
xl2tpd version:  xl2tpd-1.3.14

**Comment by rjurney** [comment]
It is not reachable for me either.

**Comment by hwdsl2** [comment]
@PierfrancescoElia Hello! This is an IKEv2 rekey bug that has been fixed in Libreswan 3.31. See https://github.com/libreswan/libreswan/issues/293. Please use the latest VPN setup scripts [1] or upgrade scripts [2] to install this version.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#installation
[2] https://github.com/hwdsl2/setup-ipsec-vpn#upgrade-libreswan
