### ISSUE TITLE
Error 809 fix?

### ISSUE THREAD

**Issue by chriseckl** [hwdsl2/setup-ipsec-vpn#770]
Is there any way of changing the config so users don't need to install the reg fix for Error 809?

I want to roll this out to a larger amount of users who don't have enough IT skills or are restricted from running elevated commands.

Is there any way of changing the config so the reg edit if not needed?

Thanks
Chris

**Comment by hwdsl2** [comment]
@chriseckl Hello! This registry change is required because Windows by default [1] "do not support Internet Protocol security (IPsec) network address translation (NAT) Traversal (NAT-T) security associations to servers that are located behind a NAT device." Unfortunately, I am not aware of a workaround for this.

[1] https://support.microsoft.com/en-us/help/926179/how-to-configure-an-l2tp-ipsec-server-behind-a-nat-t-device-in-windows
