### ISSUE TITLE
FreeBSD (PfSense) client instructions

### ISSUE THREAD

**Issue by scj643** [hwdsl2/setup-ipsec-vpn#81]
Would it be possible to add instructions for setting up freebsd (In my case pfsense) as a client?

**Comment by hwdsl2** [comment]
@scj643 IPSec + L2TP may be broken under pfSense. Instead of the IPsec VPN server, try setting up an OpenVPN server using Nyr's script [1], and configure pfSense as a client [2].

[1] https://github.com/Nyr/openvpn-install
[2] https://serverfault.com/questions/579375/how-do-i-configure-pfsense-as-an-outbound-vpn-client
