### ISSUE TITLE
Outbound problem

### ISSUE THREAD

**Issue by EmreCaliskan1** [hwdsl2/setup-ipsec-vpn#810]
Hello

Plesk obsidian 18 with Centos 8 installed server 

Fedora 32 connected vpn but only local network , not working outbound internet.

same problem exists windows, macos, iphone , android. 

but throw them away when they are not connected to the external network.

**Comment by hwdsl2** [comment]
@EmreCaliskan1 Hello! On your CentOS 8 server, what is the output of:
```
nft list ruleset
```

**Comment by hwdsl2** [comment]
@EmreCaliskan1 Closing this because the VPN scripts are intended for use on a freshly installed Ubuntu/Debian/CentOS server. Running it on a Plesk server is not supported. For uninstallation instructions, see README in this repo. I would suggest that you re-run the script on another freshly installed server.
