### ISSUE TITLE
Error during Libreswan 3.18 build

### ISSUE THREAD

**Issue by mike362** [hwdsl2/setup-ipsec-vpn#82]
Just tried to run the install script using the Option 1 approach on a Centos 6 vps which has failed as noted above. The console output text is contained in the attached file for info. Before running the script I ran yum update successfully and rebooted the vps.
[VPN Build Error - Console Output.pdf](https://github.com/hwdsl2/setup-ipsec-vpn/files/562775/VPN.Build.Error.-.Console.Output.pdf)

**Comment by hwdsl2** [comment]
@mike362 Your VPS server does not have enough RAM, Libreswan compilation was interrupted (killed) due to out of memory. See this line in the output:

```
/usr/bin/xmlto: line 576: 3678 Killed ...
```

To resolve this issue, try one of these options:

1. Stop other running processes to free up RAM, then re-run the VPN setup script.
2. Create a swap file on your VPS. See: [1] [2].
3. Upgrade your VPS to larger RAM.

[1] https://serverfault.com/questions/218750/why-dont-ec2-ubuntu-images-have-swap
[2] https://stackoverflow.com/questions/17173972/how-do-you-add-swap-to-an-ec2-instance

**Comment by mike362** [comment]
Thanks for diagnosing the error for me and the suggestions, I’ll take a look at swap space.

Great job with the scripts.

Mike
