### ISSUE TITLE
documentation: leave note somewhere that OSX Big Sur 11.0 is broken

### ISSUE THREAD

**Issue by letoams** [hwdsl2/setup-ipsec-vpn#894]
Just a note for someone to update the docs/FAQ that OSX Big Sur 11.0 is broken for IPsec (at least IKEv1 XAUTH, aka "csco ipsec" mode but possibly more. It is fixed in Big Sur 11.1

**Comment by hwdsl2** [comment]
Thanks @letoams, I'll add it to the documentation.

**Comment by hwdsl2** [comment]
@letoams FYI, I looked into the macOS Big Sur VPN issues, it seems that setting `sha2-truncbug=no` would fix it. The VPN setup scripts are already using this setting since September 2019 (3353888), and there's a FAQ entry for that [1]. Refer to these links from the web: [2] [3] [4].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ios-1314-and-macos-101511
[2] https://lists.libreswan.org/pipermail/swan/2020/003723.html
[3] https://support.apple.com/en-us/HT211840
[4] https://community.synology.com/enu/forum/2/post/137326

**Comment by letoams** [comment]
I don’t think that is the same issue because for iPhone and OSX you never had to set the truncbug to true ?

I think there were people who upgraded to Big Sur and then had their VPN stop working but perhaps I am wrong ?

Paul

**Comment by hwdsl2** [comment]
@letoams Agreed, it could be a different issue as you mentioned. I've added a note in ac222d4. Thanks!
