### ISSUE TITLE
Route to remote client network

### ISSUE THREAD

**Issue by Luccio96** [hwdsl2/setup-ipsec-vpn#900]
How to add static route from the l2tp server to the connected client so is possible from the server reach the client network?

**Eg**: Remote server linux <-- L2TP <-- Home firewall gateway (10.9.8.254/24) 

**Scope**: From the server ping any clients that are in the home local network.

**Comment by hwdsl2** [comment]
@Luccio96 Hello! Please refer to this earlier issue #555. After connecting using IPsec/L2TP mode, the VPN server has internal IP `192.168.42.1`, and VPN clients have internal IPs such as `192.168.42.10` (can be found in the client's VPN status). You can reach VPN client(s) from the VPN server using their assigned internal IPs.

For your specific use case, however, because this project is for setting up "road warrior" VPNs, it is generally difficult to reach other devices on the VPN client's local network from the VPN server. This might be better achieved using site-to-site VPNs, which are outside the scope of this project. Refer to the comment [1] in #555 for more information.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/555#issuecomment-487712838
