### ISSUE TITLE
Unable to connect from localhost

### ISSUE THREAD

**Issue by scialuppa** [hwdsl2/setup-ipsec-vpn#907]
Hello, I am using a program to overcome NAT in passive connection because I have an lte router.
My need is that I need the ipsec server to accept the client coming from the interface "lo" and "wlan0"
Is there a way to do this?
Thanks for a possible answer
LOG:
"packet from 127.0.0.1:51958: initial Main Mode message received but no connection has been authorized with policy PSK + IKEV1_ALLOW"
If I change the left parameter in ipsec.conf with% it tells me:
"ABORT: ASSERTION FAILED: version <elemsof (ip_types) (in ip_version_info () at ip_info.c: 126)"
"XPECTATION FAILED: found_ ||! (1) (in delete_oriented_hp () at hostpair.c: 341)"
"both sides of" l2tp-psk "[2] 127.0.0.1 are our interface lo!"

**Comment by hwdsl2** [comment]
@scialuppa Hello! I'm not sure about your use case. Perhaps you can try putting the VPN server's public IP (instead of `127.0.0.1`) as the server address in your VPN client's configuration, if not already done so. In the default configuration, Libreswan listens on all interfaces, so accepting VPN clients coming from other interfaces generally shouldn't be a problem.

Note that the error you posted can also occur when you mix IPsec/L2TP and IPsec/XAuth mode clients from behind the same NAT. Try changing back to `left=%defaultroute`, then restarting the IPsec service: `sudo service ipsec restart`, and after that, re-connect the VPN. If not working, I suggest that you ask on the Libreswan users mailing list [1].

[1] https://lists.libreswan.org/mailman/listinfo/swan
