### ISSUE TITLE
xauth problem mode

### ISSUE THREAD

**Issue by amirabasalinaghi** [hwdsl2/setup-ipsec-vpn#920]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
hi
there is a problem when using xauth method
when I use xauth for my client I can not ssh to my server anymore(VPN works but ssh does not work)
but when I switch to PSK everything is ok

this problem is new with the last few days update 
I was running a server with an old script for months and there was no problem 
I installed the script again on a clean os and now I have this problem

**To Reproduce**

1. run script on the server
2. connect to VPN with xauth mode
3. try ssh to the server

**Expected behavior**
I should be able to connect to the server by ssh with xauth or psk

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: ubuntu 20
- Hosting provider (if applicable): hetzner

**Client (please complete the following information)**
- Device: windows and Mikrotik
- OS: win 10 and RouterOS
- VPN mode: xauth, PSK

**Additional context**

**Comment by hwdsl2** [comment]
@amirabasalinaghi Hello! This looks like a client side issue rather than a problem with the VPN setup scripts. There has been no recent updates to the setup scripts that could cause the SSH connection issue you described.

Please provide more information - how did you SSH to the VPN server after connecting to the VPN? i.e. Which IP did you use? If you used the server's internal VPN IP `192.168.42.1` for SSH, note that this IP is only valid when clients connect using IPsec/L2TP mode. The VPN server does NOT have an internal VPN IP when clients connect using IPsec/XAuth mode. In this case, what you described is normal, and as an alternative you can instead use the VPN server's public IP for SSH.
