### ISSUE TITLE
Multiple Clients cannot connect simultaneously to IKEv2

### ISSUE THREAD

**Issue by gspannu** [hwdsl2/setup-ipsec-vpn#924]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
Setup IKEv2 server successfully and generated 2 clients.
Each client _can individually connect to the server_ without any issues, however **both clients cannot connect simultaneously**. 
As I understand it - this limitation exists in L2P but not on IKEv2.

**To Reproduce**

1. Setup IKEv2 server (exactly as per the .sh files
2. Created 2 users u01 and u02 (one for iPhone and another for MAC)
3. Clients are able to connect independently - both u01 and u02
4. Connect client u01 - kept it connected and now try to connect the 2nd client u02. 
5. Unknown error occurred message appears on client machine
6. Checked auth.log for errors and it states
```
Peer ID '@u02' is not specified on the certificate SubjectAltName (SAN) and no better connection found
Feb  1 14:31:31 mini pluto[8319]: "ikev2-cp"[2] 10.21.1.1 #17: responding to IKE_AUTH message (ID 1) from 10.21.1.1:7332 with encrypted notification AUTHENTICATION_FAILED
Feb  1 14:31:31 mini pluto[8319]: "ikev2-cp"[2] 10.21.1.1 #17: encountered fatal error in state STATE_PARENT_R1

```
**Logs**
Attached text of /var/log/auth.log as log.txt

**Server (please complete the following information)**
- OS: Debian running on Mac mini (with 32-bit PAE Linux kernel as *advised* in [919](https://github.com/hwdsl2/setup-ipsec-vpn/issues/919#issuecomment-768073483))

**Client (please complete the following information)**
- Device: iPhone 12 Pro Max, MacBook Pro 2018
- OS: iOS14, Big Sur
- VPN mode: [IKEv2]

**Additional context**
See attached text from log file.
[log.txt](https://github.com/hwdsl2/setup-ipsec-vpn/files/5904564/log.txt)

**Comment by hwdsl2** [comment]
@gspannu Thank you for reporting this issue. I was able to reproduce it and identify a fix. This issue only occurs when you use an IP address (instead of a DNS name) for IKEv2 for the VPN server, and is related to Libreswan's local ID matching with different types (ID_IPV4_ADDR vs. ID_FQDN).

The fix is relatively simple. Follow these steps:

1. Edit `/etc/ipsec.d/ikev2.conf` on the VPN server. Find the line `leftid=@<your_vpn_server_ip>` and remove the `@`, so that it becomes `leftid=<your_vpn_server_ip>`.
2. Save the file and run `sudo service ipsec restart`.
3. Try to re-connect VPN client(s).

A fix for this issue will be included in an upcoming commit to the IKEv2 helper script and instructions.
