### ISSUE TITLE
阿里云服务器 IPSEC L2TP配置后 mac iOS 连接不了～

### ISSUE THREAD

**Issue by s8xym2n** [hwdsl2/setup-ipsec-vpn#938]
iOS 13  可以正常连接
iOS 14 和 macOS Big Sur 11.2.1  均连接不了

服务器设置中 UDP 500 UDP 4500 TCP 1701 都已经打开了

**Comment by s8xym2n** [comment]
问题已解决 
iOS 13/14 和 macOS 10.15/11
如果你的 iOS 13/14, macOS 10.15 (Catalina) 或者 macOS 11 (Big Sur) 设备无法连接，请尝试以下步骤：编辑 VPN 服务器上的 /etc/ipsec.conf。找到 sha2-truncbug=yes 并将它替换为 sha2-truncbug=no。保存修改并运行 service ipsec restart。然后重新连接 VPN。
---------------
但是 出现新问题 macOS iOS 无法同时连接 （iOS一个设备连接成功 其他设备都不能连接）
还有就是 不管是 macos iOS 任意一个 连接成功后 断开连接 再次连接 很长是一段时间 无法连接

**Comment by s8xym2n** [comment]
目前 L2TP  连接 4个设备 
macOS big sur 11.2
ios 11 
ios 13 
ios 14 
均可连接  但是 每个设备不能同时连接

**Comment by s8xym2n** [comment]
目前新的问题是
无法在 IPsec/XAuth ("Cisco IPsec") 模式下连接VPN服务器

iOS，macOS 都无法连接。

**Comment by s8xym2n** [comment]
又来了新问题
配置 IKEv2时 配置完成后 我无法查看我的证书 /root文件里是空的 找不到我的证书 无法传到我的设备

**Comment by hwdsl2** [comment]
@s8xym2n Hello! As mentioned in the [important notes](https://github.com/hwdsl2/setup-ipsec-vpn#important-notes), due to an IPsec/L2TP limitation, if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use only [IPsec/XAuth mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md), or [set up IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md).

Note that you cannot have both IPsec/L2TP and IPsec/XAuth ("Cisco IPsec") clients connected simultaneously from behind the same NAT. The VPN server will "remember" which mode the previously connected client used, and refuse to connect a new client using a different mode simultaneously. To "reset" Libreswan state, run `sudo service ipsec restart`.

For IKEv2, it was recently tested (see "Actions" tab in this repo) and working fine. What does the output say about the location of the client configuration file(s)? It may not be under "/root" if you used `sudo` to run the VPN scripts. Try exporting the client configuration again using e.g. `sudo bash ikev2.sh --exportclient [client name]`.

**Comment by s8xym2n** [comment]
Thank you very much!  Thank you for your answers. IKEv2 configuration is successful.

**Comment by s8xym2n** [comment]
Thank you very much!  Thank you for your answers. 
IKEv2 configuration is successful.
