### ISSUE TITLE
Unable to establish IKEv2 connection from LAN

### ISSUE THREAD

**Issue by LightMoon** [hwdsl2/setup-ipsec-vpn#975]
Hi,

I have configured the IKEv2 VPN server with the script on bare metal Centos 8. 
The VPN server is behind the NAT. Therefore,  I had to publish the VPN server and put port forwarding and DDNS in place to reach out to the server.

Good news, All working fine when the VPN connection get originated from outside of the LAN network, e.a - via mobile data.
However, I am unable to establish a successful connection whenever I try it from a client reside inside (LAN) in which the VPN server Private IP address is listening on.

I reckon the issue should be on the NFT firewall configuration which dropping the packages that originated from private source IP addresses; however, I am not sure nor have the knowledge to fix it.

Please let me know if you need me to draw a (text-based) diagram so that you can better understand the problem.

**Comment by hwdsl2** [comment]
@LightMoon Hello! Can you draw a text-based diagram of your setup? By default, the NFT rules added by the VPN setup scripts allow IPsec connections from both inside and outside the VPN server's LAN network (if any). You must use the VPN server's private IP address when connecting from inside the LAN network.

I think it could be that your VPN server has certain NFT rules that already exist before setting up the VPN, which block connections from LAN IPs. To troubleshoot further, you may post the output of:
```
nft list ruleset
```

**Comment by LightMoon** [comment]
Hi Lin,
Based on what you said, I changed the VPN client connection to use VPN server's private IP address when connecting from inside the LAN network and all went OK. However, what I want to achieve here is making a connection from inside the LAN to the public VPN Server IP address.

                                         
          LAN                            
+-----------------------------+|              
|                                                     |                                                       Internet Gateway (Public IP: 100.100.100.100)
| VPN Server - IKEv2 -                 |                                                   +--------------------------+
| with having DDNS Name           |                                                   | Ports 500 & 4500 UDP      |
| setup as identifier                      |   +-----------------------+    | Forwarded to VPN  Server |
| Private IP :   192.168.10.x          |                                                   +--------------------------+
|                                                     |   
| +-----------------------------+        

 +----------------+
 | vpn client            |    
 | (192.168.10.x)     |    Note : The DNS server will return the **Public** IP address of Internet Gateway when the client ( which 
+----------------+                is connected to LAN ) tries to get the name for VPN Server.

**Comment by hwdsl2** [comment]
@LightMoon Thanks for the details. For client devices that are inside the same LAN as the VPN server, it is recommended to connect to the server using its private (local) IP address instead of its public IP. Note that in this use case, the VPN does not provide much benefit because only traffic between the client and the VPN server is encrypted by the VPN, while traffic from the VPN server to your ISP is not.

Regarding your original question, which is to use the VPN server's public IP to connect, I tested using Debian and was able to successfully establish such a connection from a client device inside the same LAN. Just a guess, the problem could be with your router which might not correctly forward UDP ports 500 and 4500 when it receives traffic from inside the LAN.

You may add an NFT "log" rule to check whether the VPN connection attempt can reach the VPN server:
```
nft add rule filter INPUT udp dport 500 ct state new log prefix \"New IPsec connection: \"
```

After that, try to connect using the iOS VPN client while on Wi-Fi. Then check the output of `dmesg`. If the connection attempt reaches the VPN server, you'll see a new line like `New IPsec connection: ...`. Otherwise, the connection attempt did not reach the VPN server, and it's not a problem with NFT.

**Comment by LightMoon** [comment]
Thanks Lin, It seems the router is not forwarding the traffic properly.
Even the TCP dump does not show me traffic when it is originated from the LAN.

`tcpdump -ani eth0 port 500`
