### ISSUE TITLE
Bandwidth Limitation

### ISSUE THREAD

**Issue by rudiana587** [hwdsl2/setup-ipsec-vpn#981]
Hello,
Your project was very good, good job.
So i want ask about bandwidth, is there on this script was bandwidth limit on 15mbps ? i was installed on aws ec2 with region sg and badwidth spec say up to 25gbps, then i installed your script everything is good without problem and connection beetwen server client is very good with ping is about 35. I have connection about 20mbps, i was tested speed without vpn on national connection it's have 20mbps also i was tested on international (sg) connection have 20mbps, but then when speedtest with vpn on national or international (sg) is just about 15mbps, i was test with protocol l2tp, xauth, ikev2 same problem speed just 15mbps. Maybe you can help me or give same explanation about this ?

**Comment by letoams** [comment]
On Wed, 9 Jun 2021, rudiana587 wrote:

> problem and connection beetwen server client is very good with ping is about 35. I have connection about 20mbps,
> i was tested speed without vpn on national connection it's have 20mbps also i was tested on international (sg)
> connection have 20mbps, but then when speedtest with vpn on national or international (sg) is just about 15mbps,
> i was test with protocol l2tp, xauth, ikev2 same problem speed just 15mbps. Maybe you can help me or give same
> explanation about this ?

You should see a performance difference between l2tp and ikev2. If not 
than perhaps you have other issues (lower MTU due to IPsec causing 
fragmentation and sending of more packets?)

Are you using esp=aes_gcm ?

Paul

**Comment by hwdsl2** [comment]
@rudiana587 Hello! The VPN setup scripts do not set any bandwidth limit. Due to VPN overhead such as encryption, it is normal to have reduced bandwidth when using the VPN. Here are some example benchmarks [1].

As letoams@ mentioned, generally IKEv2 mode [1] would have better performance compared to IPsec/L2TP mode. The client configurations created by the IKEv2 helper script specify the AES-GCM cipher for improved performance.

[1] https://libreswan.org/wiki/Benchmarking_and_Performance_testing
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
