### ISSUE TITLE
VPN and Nginx on the same server

### ISSUE THREAD

**Issue by mrfinrod** [hwdsl2/setup-ipsec-vpn#993]
Hello!
I have installed nginx on a server that already has a VPN IKEv2 installed.

When I try to contact the server by IP address through my browser, the server does not respond.

How can I configure the firewall so that it works simultaneously with the VPN and with a regular site, which has nothing to do with VPN?

**Comment by hwdsl2** [comment]
@mrfinrod Hello! By default, the VPN setup script do not block incoming traffic (that are unrelated to the VPN) in the IPTables firewall's INPUT chain. Therefore, the issue you described is most likely not caused by the VPN script itself. It could be that your server already has certain IPTables rules set up to filter incoming traffic.

To temporarily allow incoming TCP traffic from all IPs on port 80 (for HTTP) and/or 443 (for HTTPS), run:
```
iptables -I INPUT -p tcp --dport 80 -j ACCEPT
# and/or
iptables -I INPUT -p tcp --dport 443 -j ACCEPT
```

If that works for you, you can add these commands to `/etc/rc.local` (before any "exit 0" line) to persist after reboot.
